// RUN: wafer-opt --pass-pipeline='builtin.module(wafer-lower-groups-to-instr)' %s | FileCheck %s
// RUN: wafer-opt --pass-pipeline='builtin.module(wafer-lower-groups-to-memory-planned-instr)' %s | FileCheck --check-prefix=PLANNED %s
// RUN: wafer-opt --pass-pipeline='builtin.module(wafer-lower-groups-to-ddr-memory-planned-instr)' %s | FileCheck --check-prefix=DDR-PLANNED %s

func.func @collective_reduce_scatter_to_instr(%input: tensor<8xf32>,
                                              %out: tensor<4xf32>)
    -> tensor<4xf32> {
  %group = wafer.group ins(%input : tensor<8xf32>)
      outs(%out : tensor<4xf32>) {
  ^bb0(%arg0: tensor<8xf32>, %arg1: tensor<4xf32>):
    %rs = wafer.linalg_ext.collective.reduce_scatter
        ins(%arg0 : tensor<8xf32>)
        outs(%arg1 : tensor<4xf32>)
        {
        ^bb0(%lhs: f32, %rhs: f32):
          %sum = arith.addf %lhs, %rhs : f32
          wafer.linalg_ext.collective.yield %sum : f32
        } {axis = 0 : i64, rank_group = array<i64: 0, 1>} -> tensor<4xf32>
    wafer.group.yield %rs : tensor<4xf32>
  } : tensor<4xf32>
  return %group : tensor<4xf32>
}

// CHECK-LABEL: func.func @collective_reduce_scatter_to_instr
// CHECK-NOT: wafer.group
// CHECK-NOT: wafer.linalg_ext.collective.reduce_scatter
// CHECK-NOT: wafer.tile.reduce_scatter
// CHECK: %[[INPUT:.+]] = memref.alloc
// CHECK: wafer.instr.rdma {{%.*}} to %[[INPUT]]
// CHECK: %[[RECV_BUF:.+]] = memref.alloc
// CHECK: %[[ACC:.+]] = memref.alloc
// CHECK: %[[LOCAL_SLOT:.+]] = memref.subview %[[INPUT]][0] [4] [1]
// CHECK: wafer.instr.gather_scatter %[[LOCAL_SLOT]] to %[[ACC]]
// CHECK: wafer.instr.local_fence
// CHECK: %[[SEND_SLOT:.+]] = memref.subview %[[INPUT]][4] [4] [1]
// CHECK: %[[SEND:.+]] = wafer.instr.dte_send %[[SEND_SLOT]]
// CHECK-SAME: peer = 1 : i64
// CHECK: %[[RECV:.+]] = wafer.instr.dte_recv %[[RECV_BUF]]
// CHECK-SAME: peer = 1 : i64
// CHECK: wafer.instr.dte_wait %[[SEND]], %[[RECV]]
// CHECK: wafer.instr.elementwise <add> %[[ACC]], %[[RECV_BUF]] into %[[ACC]]
// CHECK: wafer.instr.wdma

// PLANNED-LABEL: func.func @collective_reduce_scatter_to_instr
// PLANNED: memref.alloc() {wafer.spm.offset = #wafer.spm_offset<
// PLANNED: wafer.instr.dte_send
// PLANNED: wafer.instr.dte_recv
// PLANNED: wafer.instr.dte_wait
// PLANNED: wafer.instr.elementwise <add>

// DDR-PLANNED-LABEL: func.func @collective_reduce_scatter_to_instr
// DDR-PLANNED-NOT: wafer.group
// DDR-PLANNED-NOT: wafer.tile.reduce_scatter
// DDR-PLANNED: wafer.spm.offset
// DDR-PLANNED: wafer.instr.local_fence
// DDR-PLANNED: wafer.instr.dte_send
// DDR-PLANNED: wafer.instr.dte_recv
// DDR-PLANNED: wafer.instr.dte_wait
// DDR-PLANNED: wafer.instr.elementwise <add>
// DDR-PLANNED: wafer.instr.wdma
