#ifndef WAFER_COMPLETE_TILE_BARRIER_PROBE_PROTOCOL_H
#define WAFER_COMPLETE_TILE_BARRIER_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_BARRIER_TILE_COUNT UINT32_C(16)
#define WAFER_BARRIER_RESOURCE_BYTES UINT32_C(256)
#define WAFER_BARRIER_CACHE_LINE_BYTES UINT32_C(64)

#if !defined(WAFER_BARRIER_SLOTS_PER_TILE) ||                                  \
    !defined(WAFER_BARRIER_INPUT_SLOT) ||                                      \
    !defined(WAFER_BARRIER_OUTPUT_SLOT) || !defined(WAFER_BARRIER_STATUS_SLOT)
#error "barrier probe slot layout must come from the verified manifest"
#endif

#define WAFER_BARRIER_REQUEST_MAGIC UINT64_C(0x5742464352455154)
#define WAFER_BARRIER_REQUEST_WORDS UINT64_C(4)
#define WAFER_BARRIER_REQUEST_GUARD UINT64_C(0x86db3e71a5942fc0)

#define WAFER_BARRIER_RECORD_MAGIC UINT64_C(0x5742464352455354)
#define WAFER_BARRIER_RECORD_GUARD UINT64_C(0xc34a6f9128ed750b)

#define WAFER_BARRIER_INPUT_CANARY UINT8_C(0xc3)
#define WAFER_BARRIER_OUTPUT_CANARY UINT8_C(0xa5)
#define WAFER_BARRIER_EPOCH1_OFFSET UINT32_C(0)
#define WAFER_BARRIER_EPOCH2_OFFSET UINT32_C(64)
#define WAFER_BARRIER_RECORD_OFFSET UINT32_C(128)
#define WAFER_BARRIER_RECORD_WORDS UINT32_C(16)

#define WAFER_BARRIER_EPOCH1_BASE UINT64_C(0xe101ca1b00000000)
#define WAFER_BARRIER_EPOCH2_BASE UINT64_C(0xe202ca1b00000000)
#define WAFER_BARRIER_DELAY1_SCALE UINT64_C(8192)
#define WAFER_BARRIER_DELAY2_SCALE UINT64_C(6144)

#define WAFER_BARRIER_STATUS_OK UINT64_C(1)
#define WAFER_BARRIER_STATUS_INVALID_REQUEST UINT64_C(2)
#define WAFER_BARRIER_STATUS_ORACLE_FAILED UINT64_C(3)

#define WAFER_BARRIER_STEP_OUTPUT_INITIALIZED (UINT64_C(1) << 0)
#define WAFER_BARRIER_STEP_EPOCH1_WRITTEN (UINT64_C(1) << 1)
#define WAFER_BARRIER_STEP_EPOCH1_COMPLETED (UINT64_C(1) << 2)
#define WAFER_BARRIER_STEP_EPOCH1_VISIBLE (UINT64_C(1) << 3)
#define WAFER_BARRIER_STEP_EPOCH2_WRITTEN (UINT64_C(1) << 4)
#define WAFER_BARRIER_STEP_EPOCH2_COMPLETED (UINT64_C(1) << 5)
#define WAFER_BARRIER_STEP_EPOCH2_VISIBLE (UINT64_C(1) << 6)
#define WAFER_BARRIER_STEP_EPOCH1_STABLE (UINT64_C(1) << 7)
#define WAFER_BARRIER_ALL_STEPS UINT64_C(255)

enum WaferBarrierRequestWord {
  WAFER_BARRIER_REQ_MAGIC = 0,
  WAFER_BARRIER_REQ_WORD_COUNT = 1,
  WAFER_BARRIER_REQ_TILE_ID = 2,
  WAFER_BARRIER_REQ_GUARD = 3,
};

enum WaferBarrierRecordWord {
  WAFER_BARRIER_REC_MAGIC = 0,
  WAFER_BARRIER_REC_METADATA = 1,
  WAFER_BARRIER_REC_EPOCH1_MISMATCHES = 2,
  WAFER_BARRIER_REC_EPOCH2_MISMATCHES = 3,
  WAFER_BARRIER_REC_EPOCH1_CROSSTALK = 4,
  WAFER_BARRIER_REC_EPOCH1_MARKER = 5,
  WAFER_BARRIER_REC_EPOCH2_MARKER = 6,
  WAFER_BARRIER_REC_DELAY1 = 7,
  WAFER_BARRIER_REC_DELAY2 = 8,
  WAFER_BARRIER_REC_DURATION1 = 9,
  WAFER_BARRIER_REC_DURATION2 = 10,
  WAFER_BARRIER_REC_CALLS = 11,
  WAFER_BARRIER_REC_STEP_FLAGS = 12,
  WAFER_BARRIER_REC_REQUEST_GUARD = 13,
  WAFER_BARRIER_REC_PARTICIPANTS = 14,
  WAFER_BARRIER_REC_GUARD = 15,
};

#endif
