#ifndef WAFER_DDR_SPARSE_HIGH_OFFSET_PROBE_PROTOCOL_H
#define WAFER_DDR_SPARSE_HIGH_OFFSET_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_DDR_SPARSE_REQUEST_MAGIC UINT64_C(0x5744534852455154)
#define WAFER_DDR_SPARSE_RECORD_MAGIC UINT64_C(0x5744534852454344)
#define WAFER_DDR_SPARSE_ROW_MAGIC UINT64_C(0x57445348524f5721)
#define WAFER_DDR_SPARSE_REQUEST_GUARD UINT64_C(0x9b52d6407ce183af)
#define WAFER_DDR_SPARSE_RECORD_GUARD UINT64_C(0xc8642f9a15bd703e)
#define WAFER_DDR_SPARSE_ROW_GUARD UINT64_C(0x73e10ab49d5268cf)
#define WAFER_DDR_SPARSE_SCHEMA 1U

#define WAFER_DDR_SPARSE_RESOURCE_BYTES UINT32_C(0x2000)
#define WAFER_DDR_SPARSE_MIN_WORKSPACE_BYTES UINT64_C(0x900000000)
#define WAFER_DDR_SPARSE_MAX_WORKSPACE_BYTES UINT64_C(0xa00000000)
#define WAFER_DDR_SPARSE_NEAR_END_DISTANCE UINT64_C(0x80000000)
#define WAFER_DDR_SPARSE_PAYLOAD_BYTES UINT32_C(256)
#define WAFER_DDR_SPARSE_GUARD_BYTES UINT32_C(256)
#define WAFER_DDR_SPARSE_SLOT_BYTES                                    \
  (WAFER_DDR_SPARSE_PAYLOAD_BYTES + 2U * WAFER_DDR_SPARSE_GUARD_BYTES)
#define WAFER_DDR_SPARSE_OFFSET_COUNT 6U
#define WAFER_DDR_SPARSE_INPUT_BASE UINT32_C(0x200)
#define WAFER_DDR_SPARSE_ARCHIVE_BASE UINT32_C(0x400)

#define WAFER_DDR_SPARSE_SPM_SOURCE UINT64_C(0x10000)
#define WAFER_DDR_SPARSE_SPM_READBACK UINT64_C(0x20000)

#define WAFER_DDR_SPARSE_REQUEST_WORDS 16U
#define WAFER_DDR_SPARSE_HEADER_WORDS 16U
#define WAFER_DDR_SPARSE_ROW_WORDS 8U
#define WAFER_DDR_SPARSE_RECORD_BYTES                                \
  ((WAFER_DDR_SPARSE_HEADER_WORDS +                                  \
    WAFER_DDR_SPARSE_OFFSET_COUNT * WAFER_DDR_SPARSE_ROW_WORDS) * 8U)

enum WaferDDRSparseStatus {
  WAFER_DDR_SPARSE_STATUS_OK = 0,
  WAFER_DDR_SPARSE_STATUS_BAD_REQUEST = 1,
  WAFER_DDR_SPARSE_STATUS_BAD_BINDING = 2,
  WAFER_DDR_SPARSE_STATUS_ADDRESS_OVERFLOW = 3,
};

enum WaferDDRSparseRequestWord {
  WAFER_DDR_SPARSE_REQ_MAGIC = 0,
  WAFER_DDR_SPARSE_REQ_SCHEMA = 1,
  WAFER_DDR_SPARSE_REQ_SAMPLE = 2,
  WAFER_DDR_SPARSE_REQ_WORKSPACE_BYTES = 3,
  WAFER_DDR_SPARSE_REQ_RESOURCE_BYTES = 4,
  WAFER_DDR_SPARSE_REQ_PAYLOAD_BYTES = 5,
  WAFER_DDR_SPARSE_REQ_GUARD_BYTES = 6,
  WAFER_DDR_SPARSE_REQ_OFFSET_COUNT = 7,
  WAFER_DDR_SPARSE_REQ_GUARD = 15,
};

enum WaferDDRSparseHeaderWord {
  WAFER_DDR_SPARSE_HDR_MAGIC = 0,
  WAFER_DDR_SPARSE_HDR_SCHEMA_AND_WORDS = 1,
  WAFER_DDR_SPARSE_HDR_STATUS = 2,
  WAFER_DDR_SPARSE_HDR_SAMPLE = 3,
  WAFER_DDR_SPARSE_HDR_ROW_COUNT = 4,
  WAFER_DDR_SPARSE_HDR_WORKSPACE_BASE = 5,
  WAFER_DDR_SPARSE_HDR_WORKSPACE_BYTES = 6,
  WAFER_DDR_SPARSE_HDR_INPUT_BASE = 7,
  WAFER_DDR_SPARSE_HDR_OUTPUT_BASE = 8,
  WAFER_DDR_SPARSE_HDR_REQUEST_GUARD = 9,
  WAFER_DDR_SPARSE_HDR_PAYLOAD_BYTES = 10,
  WAFER_DDR_SPARSE_HDR_GUARD_BYTES = 11,
  WAFER_DDR_SPARSE_HDR_SLOT_BYTES = 12,
  WAFER_DDR_SPARSE_HDR_RECORD_GUARD = 15,
};

enum WaferDDRSparseRowWord {
  WAFER_DDR_SPARSE_ROW_MAGIC_WORD = 0,
  WAFER_DDR_SPARSE_ROW_INDEX = 1,
  WAFER_DDR_SPARSE_ROW_RELATIVE_OFFSET = 2,
  WAFER_DDR_SPARSE_ROW_WORKSPACE_ADDRESS = 3,
  WAFER_DDR_SPARSE_ROW_INPUT_OFFSET = 4,
  WAFER_DDR_SPARSE_ROW_ARCHIVE_OFFSET = 5,
  WAFER_DDR_SPARSE_ROW_SLOT_BYTES = 6,
  WAFER_DDR_SPARSE_ROW_GUARD_WORD = 7,
};

#endif
