#ifndef WAFER_CACHE_COHERENCE_CALIBRATION_PROBE_PROTOCOL_H
#define WAFER_CACHE_COHERENCE_CALIBRATION_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_CCH_REQUEST_MAGIC UINT64_C(0x3151455248434357)
#define WAFER_CCH_RECORD_MAGIC UINT64_C(0x3143455248434357)
#define WAFER_CCH_REQUEST_GUARD UINT64_C(0xabcdef0123456789)
#define WAFER_CCH_RECORD_GUARD UINT64_C(0x9876543210fedcba)
#define WAFER_CCH_SCHEMA 1U
#define WAFER_CCH_REQUEST_WORDS 16U
#define WAFER_CCH_RECORD_WORDS 32U
#define WAFER_CCH_RESOURCE_BYTES 65536U
#define WAFER_CCH_BODY_OFFSET 256U
#define WAFER_CCH_PAYLOAD_BYTES 16384U
#define WAFER_CCH_OUTPUT0_OFFSET 8192U
#define WAFER_CCH_OUTPUT1_OFFSET 32768U
#define WAFER_CCH_OUTPUT_CANARY UINT8_C(0xa5)
#define WAFER_CCH_SPM_GUARD_BYTES 64U
#define WAFER_CCH_SPM_A UINT64_C(0x10100)
#define WAFER_CCH_SPM_B UINT64_C(0x20100)

enum WaferCCHStatus {
  WAFER_CCH_STATUS_OK = 0,
  WAFER_CCH_STATUS_BAD_REQUEST = 1,
  WAFER_CCH_STATUS_EXECUTE_FAILED = 2,
};

enum WaferCCHRequestWord {
  WAFER_CCH_REQ_MAGIC = 0,
  WAFER_CCH_REQ_SCHEMA_AND_WORDS = 1,
  WAFER_CCH_REQ_CASE = 2,
  WAFER_CCH_REQ_SAMPLE = 3,
  WAFER_CCH_REQ_PAYLOAD_BYTES = 4,
  WAFER_CCH_REQ_EXPECTED_RDMA = 5,
  WAFER_CCH_REQ_EXPECTED_WDMA = 6,
  WAFER_CCH_REQ_RESOURCE_BYTES = 7,
  WAFER_CCH_REQ_BODY_OFFSET = 8,
  WAFER_CCH_REQ_OUTPUT0_OFFSET = 9,
  WAFER_CCH_REQ_OUTPUT1_OFFSET = 10,
  WAFER_CCH_REQ_GUARD = 15,
};

enum WaferCCHRecordWord {
  WAFER_CCH_REC_MAGIC = 0,
  WAFER_CCH_REC_SCHEMA_AND_WORDS = 1,
  WAFER_CCH_REC_STATUS = 2,
  WAFER_CCH_REC_CASE = 3,
  WAFER_CCH_REC_SAMPLE = 4,
  WAFER_CCH_REC_PAYLOAD_BYTES = 5,
  WAFER_CCH_REC_EXPECTED_RDMA = 6,
  WAFER_CCH_REC_EXPECTED_WDMA = 7,
  WAFER_CCH_REC_REQUEST_GUARD = 8,
  WAFER_CCH_REC_OUTPUT0_OFFSET = 9,
  WAFER_CCH_REC_OUTPUT1_OFFSET = 10,
  WAFER_CCH_REC_MISMATCH_BEFORE = 11,
  WAFER_CCH_REC_MISMATCH_AFTER = 12,
  WAFER_CCH_REC_SPM_GUARD_MISMATCHES = 13,
  WAFER_CCH_REC_OUTPUT_GUARD_MISMATCHES = 14,
  WAFER_CCH_REC_RDMA_INST_DELTA = 15,
  WAFER_CCH_REC_WDMA_INST_DELTA = 16,
  WAFER_CCH_REC_CACHE_CONTROL_MASK = 17,
  WAFER_CCH_REC_RDMA_EXEC_DELTA = 18,
  WAFER_CCH_REC_WDMA_EXEC_DELTA = 19,
  WAFER_CCH_REC_RECORD_GUARD = 31,
};

#endif
