#ifndef WAFER_DATAMOVE_EXTENDED_CALIBRATION_PROBE_PROTOCOL_H
#define WAFER_DATAMOVE_EXTENDED_CALIBRATION_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_DMX_REQUEST_MAGIC UINT64_C(0x325145584d444357)
#define WAFER_DMX_RECORD_MAGIC UINT64_C(0x324345584d444357)
#define WAFER_DMX_REQUEST_GUARD UINT64_C(0xc6b5a4938271605f)
#define WAFER_DMX_RECORD_GUARD UINT64_C(0x2132435465768798)
#define WAFER_DMX_REQUEST_WORDS 24U
#define WAFER_DMX_RECORD_WORDS 48U
#define WAFER_DMX_RESOURCE_BYTES 262144U
#define WAFER_DMX_SLOT_BYTES 131072U
#define WAFER_DMX_BODY_OFFSET 512U
#define WAFER_DMX_OUTPUT_DDR_OFFSET WAFER_DMX_SLOT_BYTES
#define WAFER_DMX_SLOT_CANARY UINT8_C(0xa7)

#define WAFER_DMX_SPM_INPUT UINT64_C(0x10000)
#define WAFER_DMX_SPM_OUTPUT UINT64_C(0x40000)
#define WAFER_DMX_SPM_AUX0 UINT64_C(0x70000)
#define WAFER_DMX_SPM_AUX1 UINT64_C(0x90000)

enum WaferDMXStatus {
  WAFER_DMX_STATUS_OK = 0,
  WAFER_DMX_STATUS_BAD_REQUEST = 1,
  WAFER_DMX_STATUS_EXECUTE_FAILED = 2,
};

enum WaferDMXOracle {
  WAFER_DMX_ORACLE_EXACT = 0,
  WAFER_DMX_ORACLE_OBSERVATION = 1,
};

enum WaferDMXRequestWord {
  WAFER_DMX_REQ_MAGIC = 0,
  WAFER_DMX_REQ_WORD_COUNT = 1,
  WAFER_DMX_REQ_CASE = 2,
  WAFER_DMX_REQ_INPUT_BYTES = 3,
  WAFER_DMX_REQ_RESULT_BYTES = 4,
  WAFER_DMX_REQ_OUTPUT_SPAN = 5,
  WAFER_DMX_REQ_TDMA_INSTRUCTIONS = 6,
  WAFER_DMX_REQ_CT_INSTRUCTIONS = 7,
  WAFER_DMX_REQ_NE_INSTRUCTIONS = 8,
  WAFER_DMX_REQ_ORACLE = 9,
  WAFER_DMX_REQ_SAMPLE = 10,
  WAFER_DMX_REQ_RESOURCE_BYTES = 11,
  WAFER_DMX_REQ_SLOT_BYTES = 12,
  WAFER_DMX_REQ_BODY_OFFSET = 13,
  WAFER_DMX_REQ_GUARD = 23,
};

enum WaferDMXRecordWord {
  WAFER_DMX_REC_MAGIC = 0,
  WAFER_DMX_REC_WORD_COUNT = 1,
  WAFER_DMX_REC_STATUS = 2,
  WAFER_DMX_REC_CASE = 3,
  WAFER_DMX_REC_INPUT_BYTES = 4,
  WAFER_DMX_REC_RESULT_BYTES = 5,
  WAFER_DMX_REC_OUTPUT_SPAN = 6,
  WAFER_DMX_REC_TDMA_INSTRUCTIONS = 7,
  WAFER_DMX_REC_CT_INSTRUCTIONS = 8,
  WAFER_DMX_REC_NE_INSTRUCTIONS = 9,
  WAFER_DMX_REC_ORACLE = 10,
  WAFER_DMX_REC_SAMPLE = 11,
  WAFER_DMX_REC_REQUEST_GUARD = 12,
  WAFER_DMX_REC_OUTPUT_DDR_OFFSET = 13,
  WAFER_DMX_REC_SLOT_BYTES = 14,
  WAFER_DMX_REC_BODY_OFFSET = 15,
  WAFER_DMX_REC_OUTPUT_GUARD_MISMATCHES = 16,
  WAFER_DMX_REC_TDMA_INST_DELTA = 17,
  WAFER_DMX_REC_CT_INST_DELTA = 18,
  WAFER_DMX_REC_NE_INST_DELTA = 19,
  WAFER_DMX_REC_TDMA_EXEC_DELTA = 20,
  WAFER_DMX_REC_CT_EXEC_DELTA = 21,
  WAFER_DMX_REC_NE_EXEC_DELTA = 22,
  WAFER_DMX_REC_RAW_EXECUTE_RC = 23,
  WAFER_DMX_REC_RECORD_GUARD = 47,
};

#endif
