#ifndef WAFER_SPM_CROSS_TILE_CONFLICT_PROBE_PROTOCOL_H
#define WAFER_SPM_CROSS_TILE_CONFLICT_PROBE_PROTOCOL_H

#include <stdint.h>

/*
 * The cross-tile envelope carries two ordinary memory-descriptor requests.
 * Keeping the serial and window controls in one launch gives both controls
 * the same Tile-local DDR allocations.  The underlying request and result
 * records remain governed by wafer_memory_descriptor_calibration_probe_protocol.h.
 */
#define WAFER_SPM_CT_REQUEST_MAGIC UINT64_C(0x31515443504d5357)
#define WAFER_SPM_CT_RECORD_MAGIC UINT64_C(0x31524343504d5357)
#define WAFER_SPM_CT_REQUEST_GUARD UINT64_C(0x7be143a592d06fc8)
#define WAFER_SPM_CT_RECORD_GUARD UINT64_C(0x49c5e270a6138bdf)
#define WAFER_SPM_CT_TILES 16U
#define WAFER_SPM_CT_COUNTERBALANCED_ROUNDS 4U

#define WAFER_SPM_CT_SERIAL_REQUEST_WORD 0U
#define WAFER_SPM_CT_WINDOW_REQUEST_WORD 40U
#define WAFER_SPM_CT_REQUEST_META_WORD 80U
#define WAFER_SPM_CT_REQUEST_META_WORDS 20U

/* The ordinary MDC result owns words [0, 64). */
#define WAFER_SPM_CT_RECORD_META_WORD 64U
#define WAFER_SPM_CT_RECORD_META_WORDS 21U

enum WaferSPMCTTileOrder {
  WAFER_SPM_CT_TILE_ORDER_FORWARD = 0,
  WAFER_SPM_CT_TILE_ORDER_REVERSE = 1,
};

enum WaferSPMCTStatus {
  WAFER_SPM_CT_STATUS_OK = 0,
  WAFER_SPM_CT_STATUS_BAD_ENVELOPE = 1,
  WAFER_SPM_CT_STATUS_BAD_PAIR = 2,
};

enum WaferSPMCTRequestMetaWord {
  WAFER_SPM_CT_REQ_MAGIC = 0,
  WAFER_SPM_CT_REQ_WORD_COUNT = 1,
  WAFER_SPM_CT_REQ_TILE_ID = 2,
  WAFER_SPM_CT_REQ_TILE_COUNT = 3,
  WAFER_SPM_CT_REQ_COORDINATE = 4,
  WAFER_SPM_CT_REQ_SERIAL_CASE = 5,
  WAFER_SPM_CT_REQ_WINDOW_CASE = 6,
  WAFER_SPM_CT_REQ_SERIAL_REQUEST_WORD = 7,
  WAFER_SPM_CT_REQ_WINDOW_REQUEST_WORD = 8,
  WAFER_SPM_CT_REQ_SPM_A = 9,
  WAFER_SPM_CT_REQ_SPM_B = 10,
  WAFER_SPM_CT_REQ_TRANSFER_BYTES = 11,
  WAFER_SPM_CT_REQ_ISSUE_ORDER = 12,
  WAFER_SPM_CT_REQ_SAMPLE = 13,
  WAFER_SPM_CT_REQ_RESOURCE_BYTES = 14,
  WAFER_SPM_CT_REQ_GUARD = 15,
  WAFER_SPM_CT_REQ_EXECUTION_ROUND = 16,
  WAFER_SPM_CT_REQ_TILE_ORDER = 17,
  WAFER_SPM_CT_REQ_TILE_PHASE = 18,
  WAFER_SPM_CT_REQ_FIRST_SCHEDULE = 19,
};

enum WaferSPMCTRecordMetaWord {
  WAFER_SPM_CT_REC_MAGIC = 0,
  WAFER_SPM_CT_REC_WORD_COUNT = 1,
  WAFER_SPM_CT_REC_STATUS = 2,
  WAFER_SPM_CT_REC_TILE_ID = 3,
  WAFER_SPM_CT_REC_TILE_COUNT = 4,
  WAFER_SPM_CT_REC_COORDINATE = 5,
  WAFER_SPM_CT_REC_INNER_CASE = 6,
  WAFER_SPM_CT_REC_SCHEDULE = 7,
  WAFER_SPM_CT_REC_REQUEST_DDR = 8,
  WAFER_SPM_CT_REC_PAYLOAD_DDR = 9,
  WAFER_SPM_CT_REC_OUTPUT_DDR = 10,
  WAFER_SPM_CT_REC_SPM_A = 11,
  WAFER_SPM_CT_REC_SPM_B = 12,
  WAFER_SPM_CT_REC_SAMPLE = 13,
  WAFER_SPM_CT_REC_REQUEST_GUARD = 14,
  WAFER_SPM_CT_REC_RECORD_GUARD = 15,
  WAFER_SPM_CT_REC_EXECUTION_ROUND = 16,
  WAFER_SPM_CT_REC_TILE_ORDER = 17,
  WAFER_SPM_CT_REC_TILE_PHASE = 18,
  WAFER_SPM_CT_REC_FIRST_SCHEDULE = 19,
  WAFER_SPM_CT_REC_EXECUTION_ORDINAL = 20,
};

#endif
