#ifndef WAFER_NE_CALIBRATION_PROBE_PROTOCOL_H
#define WAFER_NE_CALIBRATION_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_NEC_REQUEST_MAGIC UINT64_C(0x31514552454e4357)
#define WAFER_NEC_RECORD_MAGIC UINT64_C(0x31434552454e4357)
#define WAFER_NEC_REQUEST_GUARD UINT64_C(0xb7a6958473625140)
#define WAFER_NEC_RECORD_GUARD UINT64_C(0x0f1e2d3c4b5a6978)
#define WAFER_NEC_SCHEMA 4U
#define WAFER_NEC_REQUEST_WORDS 24U
#define WAFER_NEC_RECORD_WORDS 32U
#define WAFER_NEC_RESOURCE_BYTES 1048576U
#define WAFER_NEC_SLOT_BYTES 262144U
#define WAFER_NEC_BODY_OFFSET 256U
#define WAFER_NEC_OUTPUT_DDR_OFFSET WAFER_NEC_SLOT_BYTES
#define WAFER_NEC_SLOT_CANARY UINT8_C(0xa7)
#define WAFER_NEC_CASE_BASE 20000U
#define WAFER_NEC_SPECIAL_CASE_BASE 21000U
#define WAFER_NEC_GEMM_OPTION_CASE_BASE 22000U
#define WAFER_NEC_CONV_CASE_BASE 23000U
#define WAFER_NEC_CONV_OPTION_CASE_BASE 23100U
#define WAFER_NEC_CONV_INDEX_CASE_BASE 23200U
#define WAFER_NEC_DEFERRED_CASE_BASE 24000U
#define WAFER_NEC_SPM_A UINT64_C(0x10000)
#define WAFER_NEC_SPM_B UINT64_C(0x50000)
#define WAFER_NEC_SPM_OUTPUT UINT64_C(0x90000)
#define WAFER_NEC_SPM_AUX UINT64_C(0xd0000)

enum WaferNECDType {
  WAFER_NEC_F16 = 0,
  WAFER_NEC_BF16 = 1,
  WAFER_NEC_I8 = 2,
};

enum WaferNECKind {
  WAFER_NEC_GEMM = 0,
  WAFER_NEC_CONV = 1,
  WAFER_NEC_DEPTHWISE_CONV = 2,
  WAFER_NEC_BACKWARD_CONV = 3,
};

enum WaferNECProfile {
  WAFER_NEC_DENSE = 0,
  WAFER_NEC_BF16_CANCELLATION = 1,
  WAFER_NEC_BF16_ROUNDING = 2,
  WAFER_NEC_BF16_SIGNED_ZERO = 3,
  WAFER_NEC_BF16_SUBNORMAL = 4,
  WAFER_NEC_BF16_OVERFLOW_INF = 5,
  WAFER_NEC_BF16_NAN = 6,
  WAFER_NEC_CONV_LARGE = 16,
  WAFER_NEC_CONV_HELDOUT = 17,
  WAFER_NEC_CONV_FEATURE_INDEX = 18,
  WAFER_NEC_CONV_WEIGHT_INDEX = 19,
  WAFER_NEC_CONV_OUTPUT_INDEX = 20,
  WAFER_NEC_GEMM_QUANT = 32,
  WAFER_NEC_GEMM_L1_R2 = 33,
  WAFER_NEC_GEMM_L2_R1 = 34,
  WAFER_NEC_DEPTHWISE_1X1 = 35,
  WAFER_NEC_BACKWARD_1X1 = 36,
};

enum WaferNECOption {
  WAFER_NEC_OPTION_NONE = 0,
  WAFER_NEC_OPTION_BIAS = 1,
  WAFER_NEC_OPTION_PSUM = 2,
  WAFER_NEC_OPTION_RELU = 3,
  WAFER_NEC_OPTION_LEAKY_RELU = 4,
  WAFER_NEC_OPTION_POSITIVE_AXIS_SCALE = 5,
  WAFER_NEC_OPTION_NEGATIVE_AXIS_SCALE = 6,
};

enum WaferNECDisposition {
  WAFER_NEC_BOARD_EXACT = 0,
  WAFER_NEC_BOARD_OBSERVED = 1,
  WAFER_NEC_ISOLATED_DEFERRED = 2,
  WAFER_NEC_STATIC_NEGATIVE = 3,
};

enum WaferNECStatus {
  WAFER_NEC_STATUS_OK = 0,
  WAFER_NEC_STATUS_BAD_REQUEST = 1,
  WAFER_NEC_STATUS_UNSUPPORTED_CASE = 2,
  WAFER_NEC_STATUS_EXECUTE_FAILED = 3,
};

enum WaferNECRequestWord {
  WAFER_NEC_REQ_MAGIC = 0,
  WAFER_NEC_REQ_SCHEMA_AND_WORDS = 1,
  WAFER_NEC_REQ_CASE = 2,
  WAFER_NEC_REQ_DTYPE = 3,
  WAFER_NEC_REQ_LHS_ORIENTATION = 4,
  WAFER_NEC_REQ_RHS_ORIENTATION = 5,
  WAFER_NEC_REQ_BATCH = 6,
  WAFER_NEC_REQ_M = 7,
  WAFER_NEC_REQ_K = 8,
  WAFER_NEC_REQ_N = 9,
  WAFER_NEC_REQ_LHS_SPAN = 10,
  WAFER_NEC_REQ_RHS_SPAN = 11,
  WAFER_NEC_REQ_OUTPUT_SPAN = 12,
  WAFER_NEC_REQ_SAMPLE = 13,
  WAFER_NEC_REQ_RESOURCE_BYTES = 14,
  WAFER_NEC_REQ_SLOT_BYTES = 15,
  WAFER_NEC_REQ_BODY_OFFSET = 16,
  WAFER_NEC_REQ_KIND = 17,
  WAFER_NEC_REQ_PROFILE = 18,
  WAFER_NEC_REQ_OPTION = 19,
  WAFER_NEC_REQ_AUX_SPAN = 20,
  WAFER_NEC_REQ_DISPOSITION = 21,
  WAFER_NEC_REQ_BATCH_PAIR = 22,
  WAFER_NEC_REQ_GUARD = 23,
};

enum WaferNECRecordWord {
  WAFER_NEC_REC_MAGIC = 0,
  WAFER_NEC_REC_SCHEMA_AND_WORDS = 1,
  WAFER_NEC_REC_STATUS = 2,
  WAFER_NEC_REC_CASE = 3,
  WAFER_NEC_REC_DTYPE = 4,
  WAFER_NEC_REC_LHS_ORIENTATION = 5,
  WAFER_NEC_REC_RHS_ORIENTATION = 6,
  WAFER_NEC_REC_BATCH = 7,
  WAFER_NEC_REC_M = 8,
  WAFER_NEC_REC_K = 9,
  WAFER_NEC_REC_N = 10,
  WAFER_NEC_REC_LHS_SPAN = 11,
  WAFER_NEC_REC_RHS_SPAN = 12,
  WAFER_NEC_REC_OUTPUT_SPAN = 13,
  WAFER_NEC_REC_SAMPLE = 14,
  WAFER_NEC_REC_EXECUTE_RESULT = 15,
  WAFER_NEC_REC_REQUEST_GUARD = 16,
  WAFER_NEC_REC_OUTPUT_DDR_OFFSET = 17,
  WAFER_NEC_REC_SLOT_BYTES = 18,
  WAFER_NEC_REC_BODY_OFFSET = 19,
  WAFER_NEC_REC_OUTPUT_GUARD_MISMATCHES = 20,
  WAFER_NEC_REC_KIND = 21,
  WAFER_NEC_REC_PROFILE = 22,
  WAFER_NEC_REC_OPTION = 23,
  WAFER_NEC_REC_AUX_SPAN = 24,
  WAFER_NEC_REC_DISPOSITION = 25,
  WAFER_NEC_REC_LHS_BATCH = 26,
  WAFER_NEC_REC_RHS_BATCH = 27,
  WAFER_NEC_REC_RECORD_GUARD = 31,
};

#endif
