#ifndef WAFER_CACHE_COHERENCE_CALIBRATION_PROBE_PROTOCOL_H
#define WAFER_CACHE_COHERENCE_CALIBRATION_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_CCH_REQUEST_MAGIC UINT64_C(0x3151455248434357)
#define WAFER_CCH_RECORD_MAGIC UINT64_C(0x3143455248434357)
#define WAFER_CCH_REQUEST_GUARD UINT64_C(0xabcdef0123456789)
#define WAFER_CCH_RECORD_GUARD UINT64_C(0x9876543210fedcba)
#define WAFER_CCH_REQUEST_WORDS 24U
#define WAFER_CCH_RECORD_WORDS 32U
#define WAFER_CCH_RESOURCE_BYTES 65536U
#define WAFER_CCH_BODY_OFFSET 256U
#define WAFER_CCH_PAYLOAD_BYTES 16384U
#define WAFER_CCH_OUTPUT0_OFFSET 8192U
#define WAFER_CCH_OUTPUT1_OFFSET 32768U
#define WAFER_CCH_OUTPUT_CANARY UINT8_C(0xa5)
#define WAFER_CCH_SPM_GUARD_BYTES 64U
#define WAFER_CCH_SPM_A UINT64_C(0x10100)
#define WAFER_CCH_SPM_B UINT64_C(0x20100)
#define WAFER_CCH_BANK_PAYLOAD_BYTES 4096U
#define WAFER_CCH_BANK_REGION_GAP 8192U
#define WAFER_CCH_BANK_PMU_REPETITIONS 3U
#define WAFER_CCH_BANK_SLOT_BYTES                                           \
  (WAFER_CCH_BANK_PAYLOAD_BYTES + 2U * WAFER_CCH_SPM_GUARD_BYTES)
#define WAFER_CCH_BANK_SEED_RDMA_INSTRUCTIONS 2U
#define WAFER_CCH_BANK_READBACK_WDMA_INSTRUCTIONS 2U
#define WAFER_CCH_CONFLICT_MODE 1U
#define WAFER_CCH_CONFLICT_FIRST_CASE_ID 1000U
#define WAFER_CCH_CONFLICT_REPETITIONS 4U
#define WAFER_CCH_CONFLICT_SCHEDULES 2U
#define WAFER_CCH_CONFLICT_ISSUE_ORDERS 2U
#define WAFER_CCH_CONFLICT_BATCH_ROWS                                  \
  (WAFER_CCH_CONFLICT_REPETITIONS * WAFER_CCH_CONFLICT_SCHEDULES *    \
   WAFER_CCH_CONFLICT_ISSUE_ORDERS)
#define WAFER_CCH_CONFLICT_DATA_BASE 8192U
#define WAFER_CCH_CONFLICT_ARCHIVE_BASE 8192U
#define WAFER_CCH_CONFLICT_ARCHIVE_STRIDE 8448U
#define WAFER_CCH_CONFLICT_ROW_MAGIC UINT64_C(0x5743434844524f57)
#define WAFER_CCH_CONFLICT_ROW_GUARD UINT64_C(0xa18e42c7956b30df)
#define WAFER_CCH_CONFLICT_ROW_WORDS 18U
#define WAFER_CCH_CONFLICT_RECORD_BYTES                                \
  ((WAFER_CCH_RECORD_WORDS +                                           \
    WAFER_CCH_CONFLICT_BATCH_ROWS * WAFER_CCH_CONFLICT_ROW_WORDS) * 8U)

enum WaferCCHConflictBaseRelation {
  WAFER_CCH_CONFLICT_BASE_SAME_ALLOCATION = 1,
  WAFER_CCH_CONFLICT_BASE_CROSS_ALLOCATION = 2,
};

enum WaferCCHStatus {
  WAFER_CCH_STATUS_OK = 0,
  WAFER_CCH_STATUS_BAD_REQUEST = 1,
  WAFER_CCH_STATUS_EXECUTE_FAILED = 2,
};

enum WaferCCHRequestWord {
  WAFER_CCH_REQ_MAGIC = 0,
  WAFER_CCH_REQ_WORD_COUNT = 1,
  WAFER_CCH_REQ_CASE = 2,
  WAFER_CCH_REQ_SAMPLE = 3,
  WAFER_CCH_REQ_PAYLOAD_BYTES = 4,
  WAFER_CCH_REQ_EXPECTED_RDMA = 5,
  WAFER_CCH_REQ_EXPECTED_WDMA = 6,
  WAFER_CCH_REQ_RESOURCE_BYTES = 7,
  WAFER_CCH_REQ_BODY_OFFSET = 8,
  WAFER_CCH_REQ_OUTPUT0_OFFSET = 9,
  WAFER_CCH_REQ_OUTPUT1_OFFSET = 10,
  WAFER_CCH_REQ_PAIR_KIND = 11,
  WAFER_CCH_REQ_SCHEDULE = 12,
  WAFER_CCH_REQ_BANK_OFFSET = 13,
  WAFER_CCH_REQ_MODE = 14,
  WAFER_CCH_REQ_TRANSFER_BYTES = 15,
  WAFER_CCH_REQ_BASE_RELATION = 16,
  WAFER_CCH_REQ_BASE_TRANSLATION = 17,
  WAFER_CCH_REQ_REPETITIONS = 18,
  WAFER_CCH_REQ_BATCH_ROWS = 19,
  WAFER_CCH_REQ_ARCHIVE_BASE = 20,
  WAFER_CCH_REQ_ARCHIVE_STRIDE = 21,
  WAFER_CCH_REQ_GUARD = 23,
};

enum WaferCCHRecordWord {
  WAFER_CCH_REC_MAGIC = 0,
  WAFER_CCH_REC_WORD_COUNT = 1,
  WAFER_CCH_REC_STATUS = 2,
  WAFER_CCH_REC_CASE = 3,
  WAFER_CCH_REC_SAMPLE = 4,
  WAFER_CCH_REC_PAYLOAD_BYTES = 5,
  WAFER_CCH_REC_EXPECTED_RDMA = 6,
  WAFER_CCH_REC_EXPECTED_WDMA = 7,
  WAFER_CCH_REC_REQUEST_GUARD = 8,
  WAFER_CCH_REC_OUTPUT0_OFFSET = 9,
  WAFER_CCH_REC_OUTPUT1_OFFSET = 10,
  WAFER_CCH_REC_MISMATCH_BEFORE = 11,
  WAFER_CCH_REC_MISMATCH_AFTER = 12,
  WAFER_CCH_REC_SPM_GUARD_MISMATCHES = 13,
  WAFER_CCH_REC_OUTPUT_GUARD_MISMATCHES = 14,
  WAFER_CCH_REC_RDMA_INST_DELTA = 15,
  WAFER_CCH_REC_WDMA_INST_DELTA = 16,
  WAFER_CCH_REC_CACHE_CONTROL_MASK = 17,
  WAFER_CCH_REC_RDMA_EXEC_DELTA = 18,
  WAFER_CCH_REC_WDMA_EXEC_DELTA = 19,
  WAFER_CCH_REC_PAIR_KIND = 20,
  WAFER_CCH_REC_SCHEDULE = 21,
  WAFER_CCH_REC_BANK_OFFSET = 22,
  WAFER_CCH_REC_MODE = 23,
  WAFER_CCH_REC_TRANSFER_BYTES = 24,
  WAFER_CCH_REC_BASE_RELATION = 25,
  WAFER_CCH_REC_BASE_TRANSLATION = 26,
  WAFER_CCH_REC_DDR_BASE_A = 27,
  WAFER_CCH_REC_DDR_BASE_B = 28,
  WAFER_CCH_REC_DDR_ADDRESS_A = 29,
  WAFER_CCH_REC_DDR_ADDRESS_B = 30,
  WAFER_CCH_REC_RECORD_GUARD = 31,
};

enum WaferCCHConflictRowWord {
  WAFER_CCH_CONFLICT_ROW_MAGIC_WORD = 0,
  WAFER_CCH_CONFLICT_ROW_IDENTITY = 1,
  WAFER_CCH_CONFLICT_ROW_REPETITION = 2,
  WAFER_CCH_CONFLICT_ROW_SCHEDULE = 3,
  WAFER_CCH_CONFLICT_ROW_ISSUE_ORDER = 4,
  WAFER_CCH_CONFLICT_ROW_RDMA_INST_DELTA = 5,
  WAFER_CCH_CONFLICT_ROW_WDMA_INST_DELTA = 6,
  WAFER_CCH_CONFLICT_ROW_RDMA_EXEC_DELTA = 7,
  WAFER_CCH_CONFLICT_ROW_WDMA_EXEC_DELTA = 8,
  WAFER_CCH_CONFLICT_ROW_PLAN_CYCLES = 9,
  WAFER_CCH_CONFLICT_ROW_ARCHIVE0_OFFSET = 10,
  WAFER_CCH_CONFLICT_ROW_ARCHIVE1_OFFSET = 11,
  WAFER_CCH_CONFLICT_ROW_DDR_ADDRESS_A = 12,
  WAFER_CCH_CONFLICT_ROW_DDR_ADDRESS_B = 13,
  WAFER_CCH_CONFLICT_ROW_COMPLETED = 14,
  WAFER_CCH_CONFLICT_ROW_GUARD_WORD = 15,
  WAFER_CCH_CONFLICT_ROW_RESULT_MISMATCHES = 16,
  WAFER_CCH_CONFLICT_ROW_SCHEDULE_POSITION = 17,
};

#endif
