#ifndef WAFER_WORKER_PLACEMENT_PROBE_PROTOCOL_H
#define WAFER_WORKER_PLACEMENT_PROBE_PROTOCOL_H

#include <stdint.h>

/*
 * Wire contract for program-local worker placement/progress characterization.
 *
 * The contract intentionally exposes only observations available from the
 * current target: one common device-cycle window, per-worker instruction and
 * blocking counters, raw CONTROL/IB_COUNTER samples, rotating first-observed
 * task-done polling, matching-worker completion, and exact guarded results.
 * First-observed cycles are polling observations, not hardware completion
 * timestamps, and the contract does not name a physical arbiter policy.
 */

#define WAFER_WP_REQUEST_MAGIC UINT64_C(0x3151455250574657)
#define WAFER_WP_RECORD_MAGIC UINT64_C(0x3143455250574657)
#define WAFER_WP_REQUEST_GUARD UINT64_C(0x8a6d51c307be24f9)
#define WAFER_WP_RECORD_GUARD UINT64_C(0xe41b97c2605da83f)
#define WAFER_WP_REQUEST_WORDS 24U
#define WAFER_WP_RECORD_WORDS 288U
#define WAFER_WP_WORKERS 3U
#define WAFER_WP_QUEUES 5U
#define WAFER_WP_PMU64_COUNTERS 8U
#define WAFER_WP_MAX_ISSUES 6U
#define WAFER_WP_PLACEMENT_ISSUES 6U
#define WAFER_WP_BACKLOG_ISSUES 4U
#define WAFER_WP_OUTSTANDING_LOW_ISSUES 2U
#define WAFER_WP_OUTSTANDING_HIGH_ISSUES 6U
#define WAFER_WP_PLACEMENT_BYTES 16384U
#define WAFER_WP_RDMA_BACKLOG_BYTES 65536U
#define WAFER_WP_NE_RESULT_BYTES 16384U
#define WAFER_WP_SENTINEL_BYTES 4096U
#define WAFER_WP_LONG_ISSUE_BYTES 65536U
#define WAFER_WP_PROGRESS_SENTINEL_SPM_SLOT 4U
#define WAFER_WP_OBSERVATION_DEADLINE_CYCLES UINT64_C(1000000000)
#define WAFER_WP_CLEANUP_DEADLINE_CYCLES UINT64_C(1000000000)
#define WAFER_WP_WAIT_SUCCESS 1U
#define WAFER_WP_OUTPUT_CANARY 0xa5U
#define WAFER_WP_GUARD_BYTES 256U
#define WAFER_WP_OUTPUT_SLOT_BASE 4096U
#define WAFER_WP_OUTPUT_SLOT_DATA_BYTES 65536U
#define WAFER_WP_OUTPUT_SLOT_STRIDE                                      \
  (WAFER_WP_OUTPUT_SLOT_DATA_BYTES + 2U * WAFER_WP_GUARD_BYTES)
#define WAFER_WP_RESOURCE_BYTES                                          \
  (WAFER_WP_OUTPUT_SLOT_BASE +                                          \
   WAFER_WP_MAX_ISSUES * WAFER_WP_OUTPUT_SLOT_STRIDE)
#define WAFER_WP_SPM_SLOT_BASE UINT64_C(0x10000)
#define WAFER_WP_SPM_SLOT_STRIDE UINT64_C(0x40000)
#define WAFER_WP_SPM_READ0_OFFSET UINT64_C(0x100)
#define WAFER_WP_SPM_READ1_OFFSET UINT64_C(0x11000)
#define WAFER_WP_SPM_WRITE_OFFSET UINT64_C(0x22000)

_Static_assert(WAFER_WP_RECORD_WORDS * sizeof(uint64_t) <=
                   WAFER_WP_OUTPUT_SLOT_BASE,
               "worker record overlaps archived outputs");
_Static_assert(WAFER_WP_PROGRESS_SENTINEL_SPM_SLOT <
                   WAFER_WP_MAX_ISSUES,
               "progress sentinel SPM slot exceeds owned slots");
_Static_assert(WAFER_WP_SPM_READ0_OFFSET + WAFER_WP_LONG_ISSUE_BYTES <=
                   WAFER_WP_SPM_READ1_OFFSET,
               "worker read operands overlap");
_Static_assert(WAFER_WP_SPM_READ1_OFFSET + WAFER_WP_LONG_ISSUE_BYTES <=
                   WAFER_WP_SPM_WRITE_OFFSET - WAFER_WP_GUARD_BYTES,
               "worker input overlaps the output prefix guard");
_Static_assert(WAFER_WP_SPM_WRITE_OFFSET + WAFER_WP_LONG_ISSUE_BYTES +
                       WAFER_WP_GUARD_BYTES <=
                   WAFER_WP_SPM_SLOT_STRIDE,
               "worker output exceeds its SPM slot");

enum WaferWPCaseKind {
  WAFER_WP_KIND_PLACEMENT = 0,
  WAFER_WP_KIND_BACKLOG_ONLY = 1,
  WAFER_WP_KIND_SENTINEL_ONLY = 2,
  WAFER_WP_KIND_CONCURRENT = 3,
  WAFER_WP_KIND_OUTSTANDING = 4,
};

enum WaferWPEngine {
  WAFER_WP_ENGINE_CT = 0,
  WAFER_WP_ENGINE_NE = 1,
  WAFER_WP_ENGINE_RDMA = 2,
};

enum WaferWPStatus {
  WAFER_WP_STATUS_OK = 0,
  WAFER_WP_STATUS_BAD_REQUEST = 1,
  WAFER_WP_STATUS_PREPARE_FAILED = 2,
  WAFER_WP_STATUS_ISSUE_FAILED = 3,
  WAFER_WP_STATUS_WAIT_FAILED = 4,
  WAFER_WP_STATUS_ORACLE_FAILED = 5,
  WAFER_WP_STATUS_OBSERVATION_TIMEOUT = 6,
  WAFER_WP_STATUS_CLEANUP_POISONED = 7,
};

enum WaferWPRecordFlag {
  WAFER_WP_RECORD_BEFORE_CAPTURED = UINT32_C(1) << 0,
  WAFER_WP_RECORD_ISSUES_SUBMITTED = UINT32_C(1) << 1,
  WAFER_WP_RECORD_BOUNDARY_CAPTURED = UINT32_C(1) << 2,
  WAFER_WP_RECORD_SAFETY_DRAINED = UINT32_C(1) << 3,
  WAFER_WP_RECORD_FINAL_CAPTURED = UINT32_C(1) << 4,
  WAFER_WP_RECORD_OUTPUT_ARCHIVED = UINT32_C(1) << 5,
  WAFER_WP_RECORD_MATCHING_JOIN_CONFIRMED = UINT32_C(1) << 6,
};

enum WaferWPCleanupFlag {
  WAFER_WP_CLEANUP_ATTEMPTED = UINT32_C(1) << 0,
  WAFER_WP_CLEANUP_SUCCEEDED = UINT32_C(1) << 1,
  WAFER_WP_CLEANUP_POISONED = UINT32_C(1) << 2,
};

enum WaferWPRequestWord {
  WAFER_WP_REQ_MAGIC = 0,
  WAFER_WP_REQ_WORD_COUNT = 1,
  WAFER_WP_REQ_KIND = 2,
  WAFER_WP_REQ_ENGINE = 3,
  WAFER_WP_REQ_WORKER_MASK = 4,
  WAFER_WP_REQ_TARGET_WORKER = 5,
  WAFER_WP_REQ_OBSERVER_WORKER = 6,
  WAFER_WP_REQ_SAMPLE = 7,
  WAFER_WP_REQ_WORKER0_ISSUES = 8,
  WAFER_WP_REQ_WORKER1_ISSUES = 9,
  WAFER_WP_REQ_WORKER2_ISSUES = 10,
  WAFER_WP_REQ_PRIMARY_BYTES = 11,
  WAFER_WP_REQ_SENTINEL_BYTES = 12,
  WAFER_WP_REQ_ISSUE_ROTATION = 13,
  WAFER_WP_REQ_JOIN_ROTATION = 14,
  WAFER_WP_REQ_RESOURCE_BYTES = 15,
  WAFER_WP_REQ_GUARD = 16,
  WAFER_WP_REQ_RESERVED_BASE = 17,
};

enum WaferWPRecordWord {
  WAFER_WP_REC_MAGIC = 0,
  WAFER_WP_REC_WORD_COUNT = 1,
  WAFER_WP_REC_STATUS = 2,
  WAFER_WP_REC_FLAGS = 3,
  WAFER_WP_REC_KIND = 4,
  WAFER_WP_REC_ENGINE = 5,
  WAFER_WP_REC_WORKER_MASK = 6,
  WAFER_WP_REC_TARGET_WORKER = 7,
  WAFER_WP_REC_OBSERVER_WORKER = 8,
  WAFER_WP_REC_SAMPLE = 9,
  WAFER_WP_REC_ISSUE_COUNT = 10,
  WAFER_WP_REC_PRIMARY_BYTES = 11,
  WAFER_WP_REC_SENTINEL_BYTES = 12,
  WAFER_WP_REC_REQUEST_GUARD = 13,
  WAFER_WP_REC_RECORD_GUARD = 14,
  WAFER_WP_REC_RESOURCE_BYTES = 15,
  WAFER_WP_REC_OUTPUT_SLOT_BASE = 16,
  WAFER_WP_REC_OUTPUT_SLOT_STRIDE = 17,
  WAFER_WP_REC_OUTPUT_GUARD_BYTES = 18,
  WAFER_WP_REC_PMU_ENABLE = 19,
  WAFER_WP_REC_STABLE_BEFORE = 20,
  WAFER_WP_REC_STABLE_AFTER = 21,
  WAFER_WP_REC_START_CYCLE = 22,
  WAFER_WP_REC_AFTER_ISSUE_CYCLE = 23,
  WAFER_WP_REC_OBSERVER_BOUNDARY_CYCLE = 24,
  WAFER_WP_REC_FINAL_CYCLE = 25,
  WAFER_WP_REC_OBSERVER_FIRST_DONE_CYCLES = 26,
  WAFER_WP_REC_TARGET_FIRST_DONE_CYCLES = 27,
  WAFER_WP_REC_TARGET_PENDING_BOUNDARY = 28,
  WAFER_WP_REC_OBSERVER_DONE_BOUNDARY = 29,
  WAFER_WP_REC_BOUNDARY_MISMATCHES = 30,
  WAFER_WP_REC_FINAL_MISMATCHES = 31,
  WAFER_WP_REC_FINAL_GUARD_MISMATCHES = 32,
  WAFER_WP_REC_ISSUE_WORKER_BASE = 33,
  WAFER_WP_REC_ISSUE_ENGINE_BASE = 39,
  WAFER_WP_REC_ISSUE_BYTES_BASE = 45,
  WAFER_WP_REC_ISSUE_RC_BASE = 51,
  WAFER_WP_REC_ISSUE_INTER_TYPE_BASE = 57,
  WAFER_WP_REC_CONTROL_AFTER_ISSUE = 63,
  WAFER_WP_REC_CONTROL_BOUNDARY = 66,
  WAFER_WP_REC_CONTROL_FINAL = 69,
  WAFER_WP_REC_FIRST_DONE_CYCLE_BASE = 72,
  WAFER_WP_REC_PMU64_BEFORE = 75,
  WAFER_WP_REC_PMU64_AFTER = 83,
  WAFER_WP_REC_INSTRUCTION_BEFORE = 91,
  WAFER_WP_REC_INSTRUCTION_AFTER = 106,
  WAFER_WP_REC_BLOCKING_BEFORE = 121,
  WAFER_WP_REC_BLOCKING_AFTER = 136,
  WAFER_WP_REC_OUTPUT_BYTES_BASE = 151,
  WAFER_WP_REC_OUTPUT_OFFSET_BASE = 157,
  WAFER_WP_REC_SLOT_MISMATCH_BASE = 163,
  WAFER_WP_REC_SLOT_GUARD_MISMATCH_BASE = 169,
  WAFER_WP_REC_SERIAL_MODE_BASE = 175,
  WAFER_WP_REC_CONTROL_BEFORE = 178,
  WAFER_WP_REC_CONTROL_PER_ISSUE_BASE = 181,
  WAFER_WP_REC_ISSUE_CYCLE_BASE = 199,
  WAFER_WP_REC_POLL_COUNT_BASE = 205,
  WAFER_WP_REC_MAX_POLL_GAP_BASE = 208,
  WAFER_WP_REC_POLL_ROUNDS = 211,
  WAFER_WP_REC_MATCHING_JOIN_CYCLE_BASE = 212,
  WAFER_WP_REC_MATCHING_JOIN_MASK = 215,
  WAFER_WP_REC_ISSUE_ORDINAL_BASE = 216,
  WAFER_WP_REC_ISSUE_SPM_SLOT_BASE = 222,
  WAFER_WP_REC_ISSUE_READ0_ADDRESS_BASE = 228,
  WAFER_WP_REC_ISSUE_READ1_ADDRESS_BASE = 234,
  WAFER_WP_REC_ISSUE_WRITE_ADDRESS_BASE = 240,
  WAFER_WP_REC_BOUNDARY_ORACLE_CYCLE = 246,
  WAFER_WP_REC_OBSERVATION_DEADLINE_CYCLES = 247,
  WAFER_WP_REC_OBSERVATION_TIMEOUT_MASK = 248,
  WAFER_WP_REC_OBSERVATION_TIMEOUT_CYCLE = 249,
  WAFER_WP_REC_MATCHING_JOIN_RC_BASE = 250,
  WAFER_WP_REC_MATCHING_JOIN_CONTROL_BASE = 253,
  WAFER_WP_REC_ACCEPTED_ISSUE_COUNT = 256,
  WAFER_WP_REC_ACCEPTED_WORKER_MASK = 257,
  WAFER_WP_REC_ACCEPTED_ISSUES_BY_WORKER_BASE = 258,
  WAFER_WP_REC_PENDING_WORKER_MASK = 261,
  WAFER_WP_REC_PRIMARY_FAILURE_STATUS = 262,
  WAFER_WP_REC_CLEANUP_FLAGS = 263,
  WAFER_WP_REC_CLEANUP_START_CYCLE = 264,
  WAFER_WP_REC_CLEANUP_END_CYCLE = 265,
  WAFER_WP_REC_CLEANUP_DEADLINE_CYCLES = 266,
  WAFER_WP_REC_CLEANUP_TIMEOUT_MASK = 267,
  WAFER_WP_REC_CLEANUP_ATTEMPT_COUNT = 268,
  WAFER_WP_REC_ATTEMPTED_ISSUE_COUNT = 269,
  WAFER_WP_REC_ATTEMPTED_WORKER_MASK = 270,
  WAFER_WP_REC_CLEANUP_PARTICIPANT_MASK = 271,
  WAFER_WP_REC_RESERVED_BASE = 272,
};

#endif
