#ifndef WAFER_DDR_ACTIVE_RANK_CONTENTION_PROBE_PROTOCOL_H
#define WAFER_DDR_ACTIVE_RANK_CONTENTION_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_DAR_REQUEST_MAGIC UINT64_C(0x3151455241445757)
#define WAFER_DAR_RECORD_MAGIC UINT64_C(0x3143455241445757)
#define WAFER_DAR_REQUEST_GUARD UINT64_C(0xD7146B38A925CE40)
#define WAFER_DAR_RECORD_GUARD UINT64_C(0x4EC731A9286B40D5)
#define WAFER_DAR_SCHEMA 2U
#define WAFER_DAR_REQUEST_WORDS 32U
#define WAFER_DAR_RECORD_WORDS 35U
#define WAFER_DAR_RANKS 16U
#define WAFER_DAR_GUARD_BYTES 64U
#define WAFER_DAR_INACTIVE_CANARY_BYTES 4096U
#define WAFER_DAR_RESOURCE_BYTES 2097152U
#define WAFER_DAR_MAX_CONTIGUOUS_DMA_BYTES 65536U

#define WAFER_DAR_SOURCE_OFFSET 0x20000U
#define WAFER_DAR_SEED_RDMA_OFFSET 0x00000U
#define WAFER_DAR_SEED_WDMA_OFFSET 0x40000U
#define WAFER_DAR_RDMA_ARCHIVE_OFFSET 0x10000U
#define WAFER_DAR_WDMA_TARGET_OFFSET 0x80000U
#define WAFER_DAR_SPM_RDMA UINT64_C(0x100000)
#define WAFER_DAR_SPM_WDMA UINT64_C(0x180000)

enum WaferDARDirection {
  WAFER_DAR_DIRECTION_RDMA = 1,
  WAFER_DAR_DIRECTION_WDMA = 2,
  WAFER_DAR_DIRECTION_BIDIRECTIONAL = 3,
};

enum WaferDARStatus {
  WAFER_DAR_STATUS_OK = 0,
  WAFER_DAR_STATUS_BAD_REQUEST = 1,
  WAFER_DAR_STATUS_TARGET_COUNT_MISMATCH = 2,
  WAFER_DAR_STATUS_PMU_UNSTABLE = 3,
};

enum WaferDARRequestWord {
  WAFER_DAR_REQ_MAGIC = 0,
  WAFER_DAR_REQ_SCHEMA_AND_WORDS = 1,
  WAFER_DAR_REQ_RANK = 2,
  WAFER_DAR_REQ_SAMPLE = 3,
  WAFER_DAR_REQ_ACTIVE_MASK = 4,
  WAFER_DAR_REQ_DIRECTION = 5,
  WAFER_DAR_REQ_PAYLOAD_BYTES = 6,
  WAFER_DAR_REQ_INNER_BYTES = 7,
  WAFER_DAR_REQ_STRIDE0 = 8,
  WAFER_DAR_REQ_ITERATION0 = 9,
  WAFER_DAR_REQ_EXPECTED_RDMA = 10,
  WAFER_DAR_REQ_EXPECTED_WDMA = 11,
  WAFER_DAR_REQ_ISSUE_ORDER = 12,
  WAFER_DAR_REQ_RESOURCE_BYTES = 13,
  WAFER_DAR_REQ_PAYLOAD_SEED = 14,
  WAFER_DAR_REQ_GUARD = 31,
};

enum WaferDARRecordWord {
  WAFER_DAR_REC_MAGIC = 0,
  WAFER_DAR_REC_SCHEMA_AND_WORDS = 1,
  WAFER_DAR_REC_STATUS = 2,
  WAFER_DAR_REC_RANK = 3,
  WAFER_DAR_REC_SAMPLE = 4,
  WAFER_DAR_REC_ACTIVE_MASK = 5,
  WAFER_DAR_REC_ACTIVE = 6,
  WAFER_DAR_REC_DIRECTION = 7,
  WAFER_DAR_REC_PAYLOAD_BYTES = 8,
  WAFER_DAR_REC_INNER_BYTES = 9,
  WAFER_DAR_REC_STRIDE0 = 10,
  WAFER_DAR_REC_ITERATION0 = 11,
  WAFER_DAR_REC_ENVELOPE_BYTES = 12,
  WAFER_DAR_REC_RDMA_INST_DELTA = 13,
  WAFER_DAR_REC_WDMA_INST_DELTA = 14,
  WAFER_DAR_REC_RDMA_BLOCKING_DELTA = 15,
  WAFER_DAR_REC_WDMA_BLOCKING_DELTA = 16,
  WAFER_DAR_REC_RDMA_EXEC_DELTA = 17,
  WAFER_DAR_REC_WDMA_EXEC_DELTA = 18,
  WAFER_DAR_REC_FU_EXEC_DELTA = 19,
  WAFER_DAR_REC_WINDOW_DELTA = 20,
  WAFER_DAR_REC_COMPLETION_CYCLES = 21,
  WAFER_DAR_REC_INPUT0_BASE = 22,
  WAFER_DAR_REC_INPUT1_BASE = 23,
  WAFER_DAR_REC_OUTPUT0_BASE = 24,
  WAFER_DAR_REC_OUTPUT1_BASE = 25,
  WAFER_DAR_REC_SPM_RDMA = 26,
  WAFER_DAR_REC_SPM_WDMA = 27,
  WAFER_DAR_REC_ISSUE_ORDER = 28,
  WAFER_DAR_REC_REQUEST_GUARD = 29,
  WAFER_DAR_REC_PAYLOAD_SEED = 30,
  WAFER_DAR_REC_TARGET_ONLY_WINDOW = 31,
  WAFER_DAR_REC_PMU_BEFORE_STABLE = 32,
  WAFER_DAR_REC_PMU_AFTER_STABLE = 33,
  WAFER_DAR_REC_RECORD_GUARD = 34,
};

#endif
