#ifndef WAFER_DATAMOVE_CALIBRATION_PROBE_PROTOCOL_H
#define WAFER_DATAMOVE_CALIBRATION_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_DMC_REQUEST_MAGIC UINT64_C(0x315145524d444357)
#define WAFER_DMC_RECORD_MAGIC UINT64_C(0x314345524d444357)
#define WAFER_DMC_REQUEST_GUARD UINT64_C(0xf6e5d4c3b2a1908f)
#define WAFER_DMC_RECORD_GUARD UINT64_C(0x1029384756aabbcc)
#define WAFER_DMC_REQUEST_WORDS 16U
#define WAFER_DMC_RECORD_WORDS 32U
#define WAFER_DMC_RESOURCE_BYTES 131072U
#define WAFER_DMC_SLOT_BYTES 65536U
#define WAFER_DMC_BODY_OFFSET 256U
#define WAFER_DMC_OUTPUT_DDR_OFFSET WAFER_DMC_SLOT_BYTES
#define WAFER_DMC_SLOT_CANARY UINT8_C(0xa7)
#define WAFER_DMC_SPM_INPUT UINT64_C(0x10000)
#define WAFER_DMC_SPM_OUTPUT UINT64_C(0x30000)

enum WaferDMCStatus {
  WAFER_DMC_STATUS_OK = 0,
  WAFER_DMC_STATUS_BAD_REQUEST = 1,
  WAFER_DMC_STATUS_EXECUTE_FAILED = 2,
};

enum WaferDMCRequestWord {
  WAFER_DMC_REQ_MAGIC = 0,
  WAFER_DMC_REQ_WORD_COUNT = 1,
  WAFER_DMC_REQ_CASE = 2,
  WAFER_DMC_REQ_INPUT_BYTES = 3,
  WAFER_DMC_REQ_RESULT_BYTES = 4,
  WAFER_DMC_REQ_OUTPUT_SPAN = 5,
  WAFER_DMC_REQ_EXPECTED_INSTRUCTIONS = 6,
  WAFER_DMC_REQ_SAMPLE = 7,
  WAFER_DMC_REQ_RESOURCE_BYTES = 8,
  WAFER_DMC_REQ_SLOT_BYTES = 9,
  WAFER_DMC_REQ_BODY_OFFSET = 10,
  WAFER_DMC_REQ_GUARD = 15,
};

enum WaferDMCRecordWord {
  WAFER_DMC_REC_MAGIC = 0,
  WAFER_DMC_REC_WORD_COUNT = 1,
  WAFER_DMC_REC_STATUS = 2,
  WAFER_DMC_REC_CASE = 3,
  WAFER_DMC_REC_INPUT_BYTES = 4,
  WAFER_DMC_REC_RESULT_BYTES = 5,
  WAFER_DMC_REC_OUTPUT_SPAN = 6,
  WAFER_DMC_REC_EXPECTED_INSTRUCTIONS = 7,
  WAFER_DMC_REC_SAMPLE = 8,
  WAFER_DMC_REC_REQUEST_GUARD = 9,
  WAFER_DMC_REC_OUTPUT_DDR_OFFSET = 10,
  WAFER_DMC_REC_SLOT_BYTES = 11,
  WAFER_DMC_REC_BODY_OFFSET = 12,
  /* Reserved device slot; the host validates the complete WDMA output slot. */
  WAFER_DMC_REC_OUTPUT_GUARD_MISMATCHES = 13,
  WAFER_DMC_REC_TDMA_INST_DELTA = 14,
  WAFER_DMC_REC_TDMA_EXEC_DELTA = 15,
  WAFER_DMC_REC_TDMA_BLOCKING_DELTA = 16,
  WAFER_DMC_REC_RECORD_GUARD = 31,
};

#endif
