#ifndef WAFER_NE_CALIBRATION_PROBE_PROTOCOL_H
#define WAFER_NE_CALIBRATION_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_NEC_REQUEST_MAGIC UINT64_C(0x31514552454e4357)
#define WAFER_NEC_RECORD_MAGIC UINT64_C(0x31434552454e4357)
#define WAFER_NEC_REQUEST_GUARD UINT64_C(0xb7a6958473625140)
#define WAFER_NEC_RECORD_GUARD UINT64_C(0x0f1e2d3c4b5a6978)
#define WAFER_NEC_SCHEMA 1U
#define WAFER_NEC_REQUEST_WORDS 24U
#define WAFER_NEC_RECORD_WORDS 32U
#define WAFER_NEC_RESOURCE_BYTES 262144U
#define WAFER_NEC_SLOT_BYTES 65536U
#define WAFER_NEC_BODY_OFFSET 256U
#define WAFER_NEC_OUTPUT_DDR_OFFSET WAFER_NEC_SLOT_BYTES
#define WAFER_NEC_SLOT_CANARY UINT8_C(0xa7)
#define WAFER_NEC_CASE_BASE 20000U
#define WAFER_NEC_SPM_A UINT64_C(0x10000)
#define WAFER_NEC_SPM_B UINT64_C(0x20000)
#define WAFER_NEC_SPM_OUTPUT UINT64_C(0x30000)

enum WaferNECDType {
  WAFER_NEC_F16 = 0,
  WAFER_NEC_BF16 = 1,
};

enum WaferNECStatus {
  WAFER_NEC_STATUS_OK = 0,
  WAFER_NEC_STATUS_BAD_REQUEST = 1,
  WAFER_NEC_STATUS_UNSUPPORTED_CASE = 2,
  WAFER_NEC_STATUS_EXECUTE_FAILED = 3,
};

enum WaferNECRequestWord {
  WAFER_NEC_REQ_MAGIC = 0,
  WAFER_NEC_REQ_SCHEMA_AND_WORDS = 1,
  WAFER_NEC_REQ_CASE = 2,
  WAFER_NEC_REQ_DTYPE = 3,
  WAFER_NEC_REQ_LHS_ORIENTATION = 4,
  WAFER_NEC_REQ_RHS_ORIENTATION = 5,
  WAFER_NEC_REQ_BATCH = 6,
  WAFER_NEC_REQ_M = 7,
  WAFER_NEC_REQ_K = 8,
  WAFER_NEC_REQ_N = 9,
  WAFER_NEC_REQ_LHS_SPAN = 10,
  WAFER_NEC_REQ_RHS_SPAN = 11,
  WAFER_NEC_REQ_OUTPUT_SPAN = 12,
  WAFER_NEC_REQ_SAMPLE = 13,
  WAFER_NEC_REQ_RESOURCE_BYTES = 14,
  WAFER_NEC_REQ_SLOT_BYTES = 15,
  WAFER_NEC_REQ_BODY_OFFSET = 16,
  WAFER_NEC_REQ_GUARD = 23,
};

enum WaferNECRecordWord {
  WAFER_NEC_REC_MAGIC = 0,
  WAFER_NEC_REC_SCHEMA_AND_WORDS = 1,
  WAFER_NEC_REC_STATUS = 2,
  WAFER_NEC_REC_CASE = 3,
  WAFER_NEC_REC_DTYPE = 4,
  WAFER_NEC_REC_LHS_ORIENTATION = 5,
  WAFER_NEC_REC_RHS_ORIENTATION = 6,
  WAFER_NEC_REC_BATCH = 7,
  WAFER_NEC_REC_M = 8,
  WAFER_NEC_REC_K = 9,
  WAFER_NEC_REC_N = 10,
  WAFER_NEC_REC_LHS_SPAN = 11,
  WAFER_NEC_REC_RHS_SPAN = 12,
  WAFER_NEC_REC_OUTPUT_SPAN = 13,
  WAFER_NEC_REC_SAMPLE = 14,
  WAFER_NEC_REC_EXECUTE_RESULT = 15,
  WAFER_NEC_REC_REQUEST_GUARD = 16,
  WAFER_NEC_REC_OUTPUT_DDR_OFFSET = 17,
  WAFER_NEC_REC_SLOT_BYTES = 18,
  WAFER_NEC_REC_BODY_OFFSET = 19,
  WAFER_NEC_REC_OUTPUT_GUARD_MISMATCHES = 20,
  WAFER_NEC_REC_RECORD_GUARD = 31,
};

#endif
