#ifndef WAFER_CT_CONVERT_CALIBRATION_PROBE_PROTOCOL_H
#define WAFER_CT_CONVERT_CALIBRATION_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_CTC_REQUEST_MAGIC UINT64_C(0x3151455256434357)
#define WAFER_CTC_RECORD_MAGIC UINT64_C(0x3143455256434357)
#define WAFER_CTC_REQUEST_GUARD UINT64_C(0xe7d6c5b4a3928170)
#define WAFER_CTC_RECORD_GUARD UINT64_C(0x0f1e2d3c4b5a6978)
#define WAFER_CTC_SCHEMA 2U
#define WAFER_CTC_REQUEST_WORDS 24U
#define WAFER_CTC_RECORD_WORDS 32U
#define WAFER_CTC_RESOURCE_BYTES 131072U
#define WAFER_CTC_SLOT_BYTES 65536U
#define WAFER_CTC_BODY_OFFSET 256U
#define WAFER_CTC_OUTPUT_DDR_OFFSET WAFER_CTC_SLOT_BYTES
#define WAFER_CTC_SLOT_CANARY UINT8_C(0xa7)
#define WAFER_CTC_MAIN_ELEMENTS 8192U
#define WAFER_CTC_TAIL_ELEMENTS 8197U
#define WAFER_CTC_SPM_INPUT UINT64_C(0x10000)
#define WAFER_CTC_SPM_OUTPUT UINT64_C(0x30000)

enum WaferCTCScalarType {
  WAFER_CTC_INT8 = 0,
  WAFER_CTC_INT16 = 1,
  WAFER_CTC_INT32 = 2,
  WAFER_CTC_FP16 = 3,
  WAFER_CTC_BF16 = 4,
  WAFER_CTC_FP32 = 5,
  WAFER_CTC_TF32 = 6,
};

enum WaferCTCDomain {
  WAFER_CTC_DOMAIN_NORMAL = 0,
  WAFER_CTC_DOMAIN_DIRECTED = 1,
  WAFER_CTC_DOMAIN_ZERO_POINT = 2,
  WAFER_CTC_DOMAIN_EXTREMA = 3,
  WAFER_CTC_DOMAIN_STOCHASTIC = 4,
};

enum WaferCTCDisposition {
  WAFER_CTC_BOARD_EXACT = 0,
  WAFER_CTC_BOARD_OBSERVED = 1,
  WAFER_CTC_ISOLATED_DEFERRED = 2,
};

enum WaferCTCStatus {
  WAFER_CTC_STATUS_OK = 0,
  WAFER_CTC_STATUS_BAD_REQUEST = 1,
  WAFER_CTC_STATUS_EXECUTE_FAILED = 2,
  WAFER_CTC_STATUS_UNSUPPORTED_CASE = 3,
};

enum WaferCTCRequestWord {
  WAFER_CTC_REQ_MAGIC = 0,
  WAFER_CTC_REQ_SCHEMA_AND_WORDS = 1,
  WAFER_CTC_REQ_CASE = 2,
  WAFER_CTC_REQ_OPCODE = 3,
  WAFER_CTC_REQ_SRC_TYPE = 4,
  WAFER_CTC_REQ_DST_TYPE = 5,
  WAFER_CTC_REQ_ELEMENTS = 6,
  WAFER_CTC_REQ_INPUT_BYTES = 7,
  WAFER_CTC_REQ_RESULT_BYTES = 8,
  WAFER_CTC_REQ_OUTPUT_SPAN = 9,
  WAFER_CTC_REQ_ROUNDING = 10,
  WAFER_CTC_REQ_SAMPLE = 11,
  WAFER_CTC_REQ_RESOURCE_BYTES = 12,
  WAFER_CTC_REQ_SLOT_BYTES = 13,
  WAFER_CTC_REQ_BODY_OFFSET = 14,
  WAFER_CTC_REQ_DOMAIN = 15,
  WAFER_CTC_REQ_ZERO_POINT = 16,
  WAFER_CTC_REQ_DISPOSITION = 17,
  WAFER_CTC_REQ_GUARD = 23,
};

enum WaferCTCRecordWord {
  WAFER_CTC_REC_MAGIC = 0,
  WAFER_CTC_REC_SCHEMA_AND_WORDS = 1,
  WAFER_CTC_REC_STATUS = 2,
  WAFER_CTC_REC_CASE = 3,
  WAFER_CTC_REC_OPCODE = 4,
  WAFER_CTC_REC_SRC_TYPE = 5,
  WAFER_CTC_REC_DST_TYPE = 6,
  WAFER_CTC_REC_ELEMENTS = 7,
  WAFER_CTC_REC_INPUT_BYTES = 8,
  WAFER_CTC_REC_RESULT_BYTES = 9,
  WAFER_CTC_REC_OUTPUT_SPAN = 10,
  WAFER_CTC_REC_ROUNDING = 11,
  WAFER_CTC_REC_SAMPLE = 12,
  WAFER_CTC_REC_REQUEST_GUARD = 13,
  WAFER_CTC_REC_OUTPUT_DDR_OFFSET = 14,
  WAFER_CTC_REC_SLOT_BYTES = 15,
  WAFER_CTC_REC_BODY_OFFSET = 16,
  /* Compatibility slot; the host validates the complete WDMA output slot. */
  WAFER_CTC_REC_OUTPUT_GUARD_MISMATCHES = 17,
  WAFER_CTC_REC_CT_INST_DELTA = 18,
  WAFER_CTC_REC_CT_EXEC_DELTA = 19,
  WAFER_CTC_REC_CT_BLOCKING_DELTA = 20,
  WAFER_CTC_REC_DOMAIN = 21,
  WAFER_CTC_REC_ZERO_POINT = 22,
  WAFER_CTC_REC_DISPOSITION = 23,
  WAFER_CTC_REC_RECORD_GUARD = 31,
};

#endif
