#ifndef WAFER_CT_VECTOR_CALIBRATION_PROBE_PROTOCOL_H
#define WAFER_CT_VECTOR_CALIBRATION_PROBE_PROTOCOL_H

#include <stdint.h>

/*
 * One shared package selects every CT vector opcode/form/dtype case through
 * the case id.  The case id is deliberately arithmetic so the device can
 * reconstruct the closed catalog without a second handwritten table.
 */
#define WAFER_CTV_REQUEST_MAGIC UINT64_C(0x3151455256544357)
#define WAFER_CTV_RECORD_MAGIC UINT64_C(0x3143455256544357)
#define WAFER_CTV_SCHEMA 1U
#define WAFER_CTV_REQUEST_WORDS 16U
#define WAFER_CTV_RECORD_WORDS 32U
#define WAFER_CTV_CASE_BASE 10000U
#define WAFER_CTV_CASE_STRIDE 6U
#define WAFER_CTV_RESOURCE_BYTES 131072U
#define WAFER_CTV_SLOT_BYTES 65536U
#define WAFER_CTV_BODY_OFFSET 256U
#define WAFER_CTV_OUTPUT_DDR_OFFSET 65536U
#define WAFER_CTV_SPM_A UINT64_C(0x10000)
#define WAFER_CTV_SPM_B UINT64_C(0x30000)
#define WAFER_CTV_SPM_OUTPUT UINT64_C(0x50000)
#define WAFER_CTV_SLOT_CANARY UINT8_C(0xa7)
#define WAFER_CTV_REQUEST_GUARD UINT64_C(0xc7b6a59483726150)
#define WAFER_CTV_RECORD_GUARD UINT64_C(0x8f7e6d5c4b3a2910)
#define WAFER_CTV_MAIN_ELEMENTS 8192U
#define WAFER_CTV_TAIL_ELEMENTS 8197U
#define WAFER_CTV_UNIT_ELEMENTS 37U

enum WaferCTVDisposition {
  WAFER_CTV_BOARD_EXACT = 0,
  WAFER_CTV_BOARD_TOLERANCE = 1,
  WAFER_CTV_BOARD_OBSERVED = 2,
};

enum WaferCTVDType {
  WAFER_CTV_F16 = 0,
  WAFER_CTV_BF16 = 1,
  WAFER_CTV_F32 = 2,
};

enum WaferCTVFamily {
  WAFER_CTV_UNARY = 0,
  WAFER_CTV_BINARY = 1,
  WAFER_CTV_RELATION = 2,
  WAFER_CTV_LOGIC_VALUE = 3,
  WAFER_CTV_LOGIC_BOOL = 4,
  WAFER_CTV_TRANSCENDENTAL = 5,
  WAFER_CTV_ACTIVATION = 6,
};

enum WaferCTVStatus {
  WAFER_CTV_STATUS_OK = 0,
  WAFER_CTV_STATUS_BAD_REQUEST = 1,
  WAFER_CTV_STATUS_UNSUPPORTED_CASE = 2,
  WAFER_CTV_STATUS_EXECUTE_FAILED = 3,
};

enum WaferCTVRequestWord {
  WAFER_CTV_REQ_MAGIC = 0,
  WAFER_CTV_REQ_SCHEMA_AND_WORDS = 1,
  WAFER_CTV_REQ_CASE = 2,
  WAFER_CTV_REQ_DISPOSITION = 3,
  WAFER_CTV_REQ_FAMILY = 4,
  WAFER_CTV_REQ_DTYPE = 5,
  WAFER_CTV_REQ_OPCODE = 6,
  WAFER_CTV_REQ_RESULT_BYTES = 7,
  WAFER_CTV_REQ_OUTPUT_SPAN = 8,
  WAFER_CTV_REQ_ELEMENTS = 9,
  WAFER_CTV_REQ_SAMPLE = 10,
  WAFER_CTV_REQ_RESOURCE_BYTES = 11,
  WAFER_CTV_REQ_SLOT_BYTES = 12,
  WAFER_CTV_REQ_BODY_OFFSET = 13,
  WAFER_CTV_REQ_GUARD = 15,
};

enum WaferCTVRecordWord {
  WAFER_CTV_REC_MAGIC = 0,
  WAFER_CTV_REC_SCHEMA_AND_WORDS = 1,
  WAFER_CTV_REC_STATUS = 2,
  WAFER_CTV_REC_CASE = 3,
  WAFER_CTV_REC_DISPOSITION = 4,
  WAFER_CTV_REC_FAMILY = 5,
  WAFER_CTV_REC_DTYPE = 6,
  WAFER_CTV_REC_OPCODE = 7,
  WAFER_CTV_REC_RESULT_BYTES = 8,
  WAFER_CTV_REC_OUTPUT_SPAN = 9,
  WAFER_CTV_REC_ELEMENTS = 10,
  WAFER_CTV_REC_SAMPLE = 11,
  WAFER_CTV_REC_OUTPUT_GUARD_MISMATCHES = 12,
  WAFER_CTV_REC_EXECUTE_RESULT = 13,
  WAFER_CTV_REC_REQUEST_GUARD = 14,
  WAFER_CTV_REC_OUTPUT_DDR_OFFSET = 15,
  WAFER_CTV_REC_SLOT_BYTES = 16,
  WAFER_CTV_REC_BODY_OFFSET = 17,
  WAFER_CTV_REC_INPUT_A_BYTES = 18,
  WAFER_CTV_REC_INPUT_B_BYTES = 19,
  WAFER_CTV_REC_SCALAR_BITS = 20,
  WAFER_CTV_REC_UNIT_ELEMENTS = 21,
  WAFER_CTV_REC_RECORD_GUARD = 31,
};

#endif
