#ifndef WAFER_MEMORY_DESCRIPTOR_CALIBRATION_PROBE_PROTOCOL_H
#define WAFER_MEMORY_DESCRIPTOR_CALIBRATION_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_MDC_REQUEST_MAGIC UINT64_C(0x315145444d454d57)
#define WAFER_MDC_RECORD_MAGIC UINT64_C(0x314345444d454d57)
#define WAFER_MDC_REQUEST_GUARD UINT64_C(0xb5a4938271605f4e)
#define WAFER_MDC_RECORD_GUARD UINT64_C(0x32435465768798a9)
#define WAFER_MDC_SCHEMA 3U
#define WAFER_MDC_REQUEST_WORDS 40U
#define WAFER_MDC_RECORD_WORDS 64U
#define WAFER_MDC_RESOURCE_BYTES 2097152U
#define WAFER_MDC_PAYLOAD_DATA_OFFSET 4096U
#define WAFER_MDC_OUTPUT_DATA_OFFSET 4096U
#define WAFER_MDC_OUTPUT_SINK0_OFFSET 65536U
#define WAFER_MDC_OUTPUT_SINK1_OFFSET 73728U
#define WAFER_MDC_RESOURCE_CANARY UINT8_C(0xa5)
#define WAFER_MDC_SPM_GUARD UINT8_C(0x6d)
#define WAFER_MDC_SPM_PAIR_SLOT_BYTES 2560U
#define WAFER_MDC_SPM_ALLOCATABLE_BEGIN UINT64_C(0x10000)
#define WAFER_MDC_SPM_ALLOCATABLE_END UINT64_C(0x2f0000)
#define WAFER_MDC_PERF_MAX_ROUNDS 4U
#define WAFER_MDC_PERF_MAX_BUFFERS 2U
#define WAFER_MDC_PERF_READ0_OFFSET UINT64_C(0x100)
#define WAFER_MDC_PERF_READ1_OFFSET UINT64_C(0x20100)
#define WAFER_MDC_PERF_WRITE_OFFSET UINT64_C(0x40100)
#define WAFER_MDC_PERF_DISJOINT_A UINT64_C(0x10100)
#define WAFER_MDC_PERF_DISJOINT_B UINT64_C(0x110100)
#define WAFER_MDC_PERF_PAYLOAD_BASE UINT64_C(0x20000)
#define WAFER_MDC_PERF_PAYLOAD_LANE_STRIDE UINT64_C(0x80000)
#define WAFER_MDC_PERF_PAYLOAD_READ0_OFFSET UINT64_C(0)
#define WAFER_MDC_PERF_PAYLOAD_READ1_OFFSET UINT64_C(0x20000)
#define WAFER_MDC_PERF_PAYLOAD_RDMA_OFFSET UINT64_C(0x40000)
#define WAFER_MDC_PERF_PAYLOAD_GUARD_SEED_OFFSET UINT64_C(0x140000)
#define WAFER_MDC_PERF_OUTPUT_SINK_BASE UINT64_C(0x10000)
#define WAFER_MDC_PERF_OUTPUT_RESULT_BASE UINT64_C(0x90000)
#define WAFER_MDC_PERF_OUTPUT_LANE_STRIDE UINT64_C(0x40000)
#define WAFER_MDC_PERF_OUTPUT_GUARD_BASE UINT64_C(0x190000)
#define WAFER_MDC_PERF_OUTPUT_GUARD_LANE_STRIDE UINT64_C(0x100)

enum WaferMDCKind {
  WAFER_MDC_KIND_DMA = 0,
  WAFER_MDC_KIND_ENGINE_ACCESS = 1,
  WAFER_MDC_KIND_ADDRESS_RELATION = 2,
  WAFER_MDC_KIND_ENGINE_PAIR = 3,
  WAFER_MDC_KIND_PARALLEL_PAIR = 4,
};

enum WaferMDCEngine {
  WAFER_MDC_ENGINE_CT = 0,
  WAFER_MDC_ENGINE_NE = 1,
  WAFER_MDC_ENGINE_RDMA = 2,
  WAFER_MDC_ENGINE_WDMA = 3,
  WAFER_MDC_ENGINE_TDMA = 4,
  WAFER_MDC_ENGINE_NONE = 255,
};

enum WaferMDCSchedule {
  WAFER_MDC_SCHEDULE_SERIAL = 0,
  WAFER_MDC_SCHEDULE_WINDOW = 1,
};

enum WaferMDCEffect {
  WAFER_MDC_EFFECT_NONE = 0,
  WAFER_MDC_EFFECT_RAW = 1,
  WAFER_MDC_EFFECT_WAR = 2,
  WAFER_MDC_EFFECT_WAW = 3,
  WAFER_MDC_EFFECT_RAR = 4,
};

enum WaferMDCRelation {
  WAFER_MDC_RELATION_DISJOINT = 0,
  WAFER_MDC_RELATION_EXACT = 1,
  WAFER_MDC_RELATION_PARTIAL = 2,
  WAFER_MDC_RELATION_ADJACENT = 3,
  WAFER_MDC_RELATION_STRIDED = 4,
};

enum WaferMDCOracle {
  WAFER_MDC_ORACLE_EXACT = 0,
  WAFER_MDC_ORACLE_OBSERVATION = 1,
};

enum WaferMDCStatus {
  WAFER_MDC_STATUS_OK = 0,
  WAFER_MDC_STATUS_BAD_REQUEST = 1,
  WAFER_MDC_STATUS_PREPARE_FAILED = 2,
  WAFER_MDC_STATUS_EXECUTE_FAILED = 3,
};

enum WaferMDCRecordFlag {
  WAFER_MDC_FLAG_PREPARED = UINT32_C(1) << 0,
  WAFER_MDC_FLAG_ISSUED = UINT32_C(1) << 1,
  WAFER_MDC_FLAG_COMPLETED = UINT32_C(1) << 2,
  WAFER_MDC_FLAG_READBACK = UINT32_C(1) << 3,
};

enum WaferMDCRequestWord {
  WAFER_MDC_REQ_MAGIC = 0,
  WAFER_MDC_REQ_SCHEMA_AND_WORDS = 1,
  WAFER_MDC_REQ_CASE = 2,
  WAFER_MDC_REQ_KIND = 3,
  WAFER_MDC_REQ_ENGINE_A = 4,
  WAFER_MDC_REQ_ENGINE_B = 5,
  WAFER_MDC_REQ_SCHEDULE = 6,
  WAFER_MDC_REQ_EFFECT = 7,
  WAFER_MDC_REQ_RELATION = 8,
  WAFER_MDC_REQ_ORACLE = 9,
  WAFER_MDC_REQ_FORMAT = 10,
  WAFER_MDC_REQ_SRC_DDR_OFFSET = 11,
  WAFER_MDC_REQ_DST_DDR_OFFSET = 12,
  WAFER_MDC_REQ_SPM_A = 13,
  WAFER_MDC_REQ_SPM_B = 14,
  WAFER_MDC_REQ_INNER_BYTES = 15,
  WAFER_MDC_REQ_STRIDE0 = 16,
  WAFER_MDC_REQ_STRIDE1 = 17,
  WAFER_MDC_REQ_STRIDE2 = 18,
  WAFER_MDC_REQ_ITERATION0 = 19,
  WAFER_MDC_REQ_ITERATION1 = 20,
  WAFER_MDC_REQ_ITERATION2 = 21,
  WAFER_MDC_REQ_COMPACT_BYTES = 22,
  WAFER_MDC_REQ_ENVELOPE_BYTES = 23,
  WAFER_MDC_REQ_OUTPUT_BYTES = 24,
  WAFER_MDC_REQ_SAMPLE = 25,
  WAFER_MDC_REQ_CT_INSTRUCTIONS = 26,
  WAFER_MDC_REQ_NE_INSTRUCTIONS = 27,
  WAFER_MDC_REQ_RDMA_INSTRUCTIONS = 28,
  WAFER_MDC_REQ_WDMA_INSTRUCTIONS = 29,
  WAFER_MDC_REQ_TDMA_INSTRUCTIONS = 30,
  WAFER_MDC_REQ_RESOURCE_BYTES = 31,
  WAFER_MDC_REQ_PAYLOAD_DATA_OFFSET = 32,
  WAFER_MDC_REQ_OUTPUT_DATA_OFFSET = 33,
  WAFER_MDC_REQ_WORKER_A = 34,
  WAFER_MDC_REQ_WORKER_B = 35,
  WAFER_MDC_REQ_ROUNDS = 36,
  WAFER_MDC_REQ_BUFFER_COUNT = 37,
  WAFER_MDC_REQ_ISSUE_ORDER = 38,
  WAFER_MDC_REQ_GUARD = 39,
};

enum WaferMDCRecordWord {
  WAFER_MDC_REC_MAGIC = 0,
  WAFER_MDC_REC_SCHEMA_AND_WORDS = 1,
  WAFER_MDC_REC_STATUS = 2,
  WAFER_MDC_REC_CASE = 3,
  WAFER_MDC_REC_KIND = 4,
  WAFER_MDC_REC_ENGINE_A = 5,
  WAFER_MDC_REC_ENGINE_B = 6,
  WAFER_MDC_REC_SCHEDULE = 7,
  WAFER_MDC_REC_EFFECT = 8,
  WAFER_MDC_REC_RELATION = 9,
  WAFER_MDC_REC_ORACLE = 10,
  WAFER_MDC_REC_FORMAT = 11,
  WAFER_MDC_REC_SRC_DDR_OFFSET = 12,
  WAFER_MDC_REC_DST_DDR_OFFSET = 13,
  WAFER_MDC_REC_SPM_A = 14,
  WAFER_MDC_REC_SPM_B = 15,
  WAFER_MDC_REC_INNER_BYTES = 16,
  WAFER_MDC_REC_STRIDE0 = 17,
  WAFER_MDC_REC_STRIDE1 = 18,
  WAFER_MDC_REC_STRIDE2 = 19,
  WAFER_MDC_REC_ITERATION0 = 20,
  WAFER_MDC_REC_ITERATION1 = 21,
  WAFER_MDC_REC_ITERATION2 = 22,
  WAFER_MDC_REC_COMPACT_BYTES = 23,
  WAFER_MDC_REC_ENVELOPE_BYTES = 24,
  WAFER_MDC_REC_OUTPUT_BYTES = 25,
  WAFER_MDC_REC_SAMPLE = 26,
  WAFER_MDC_REC_SPM_GUARD_MISMATCHES = 27,
  WAFER_MDC_REC_CT_INST_DELTA = 28,
  WAFER_MDC_REC_NE_INST_DELTA = 29,
  WAFER_MDC_REC_RDMA_INST_DELTA = 30,
  WAFER_MDC_REC_WDMA_INST_DELTA = 31,
  WAFER_MDC_REC_TDMA_INST_DELTA = 32,
  WAFER_MDC_REC_CT_EXEC_DELTA = 33,
  WAFER_MDC_REC_NE_EXEC_DELTA = 34,
  WAFER_MDC_REC_RDMA_EXEC_DELTA = 35,
  WAFER_MDC_REC_WDMA_EXEC_DELTA = 36,
  WAFER_MDC_REC_TDMA_EXEC_DELTA = 37,
  WAFER_MDC_REC_CT_BLOCKING_DELTA = 38,
  WAFER_MDC_REC_NE_BLOCKING_DELTA = 39,
  WAFER_MDC_REC_RDMA_BLOCKING_DELTA = 40,
  WAFER_MDC_REC_WDMA_BLOCKING_DELTA = 41,
  WAFER_MDC_REC_TDMA_BLOCKING_DELTA = 42,
  WAFER_MDC_REC_OUTPUT_DATA_OFFSET = 43,
  WAFER_MDC_REC_REQUEST_GUARD = 44,
  WAFER_MDC_REC_FLAGS = 45,
  WAFER_MDC_REC_FULL_EXEC_DELTA = 46,
  WAFER_MDC_REC_PLAN_CYCLES = 47,
  WAFER_MDC_REC_PMU_ENABLE = 48,
  WAFER_MDC_REC_SERIAL_MODE = 49,
  WAFER_MDC_REC_STABLE_BEFORE = 50,
  WAFER_MDC_REC_STABLE_AFTER = 51,
  WAFER_MDC_REC_WORKER_A = 52,
  WAFER_MDC_REC_WORKER_B = 53,
  WAFER_MDC_REC_ROUNDS = 54,
  WAFER_MDC_REC_BUFFER_COUNT = 55,
  WAFER_MDC_REC_ISSUE_ORDER = 56,
  WAFER_MDC_REC_LANE_A_WORKER_INST_DELTA = 57,
  WAFER_MDC_REC_LANE_B_WORKER_INST_DELTA = 58,
  WAFER_MDC_REC_LANE_A_WORKER_BLOCKING_DELTA = 59,
  WAFER_MDC_REC_LANE_B_WORKER_BLOCKING_DELTA = 60,
  WAFER_MDC_REC_WORKER_MASK = 61,
  WAFER_MDC_REC_CONTROL_FINAL = 62,
  WAFER_MDC_REC_RECORD_GUARD = 63,
};

#endif
