#ifndef WAFER_SPM_CALIBRATION_PROBE_PROTOCOL_H
#define WAFER_SPM_CALIBRATION_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_SPM_REQUEST_MAGIC UINT64_C(0x315145524d505357)
#define WAFER_SPM_RECORD_MAGIC UINT64_C(0x314345524d505357)
#define WAFER_SPM_REQUEST_GUARD UINT64_C(0xd7c6b5a493827160)
#define WAFER_SPM_RECORD_GUARD UINT64_C(0x1021324354657687)
#define WAFER_SPM_SCHEMA 1U
#define WAFER_SPM_REQUEST_WORDS 16U
#define WAFER_SPM_RECORD_WORDS 32U
#define WAFER_SPM_RESOURCE_BYTES 65536U
#define WAFER_SPM_SLOT_BYTES 16384U
#define WAFER_SPM_OUTPUT_DDR_OFFSET WAFER_SPM_SLOT_BYTES
#define WAFER_SPM_OUTPUT_CANARY UINT8_C(0xa5)
#define WAFER_SPM_ALLOCATABLE_BEGIN UINT64_C(0x10000)
#define WAFER_SPM_ALLOCATABLE_END UINT64_C(0x2f0000)

enum WaferSPMStatus {
  WAFER_SPM_STATUS_OK = 0,
  WAFER_SPM_STATUS_BAD_REQUEST = 1,
  WAFER_SPM_STATUS_EXECUTE_FAILED = 2,
};

enum WaferSPMRequestWord {
  WAFER_SPM_REQ_MAGIC = 0,
  WAFER_SPM_REQ_SCHEMA_AND_WORDS = 1,
  WAFER_SPM_REQ_CASE = 2,
  WAFER_SPM_REQ_ADDRESS = 3,
  WAFER_SPM_REQ_TRANSFER_BYTES = 4,
  WAFER_SPM_REQ_SAMPLE = 5,
  WAFER_SPM_REQ_RESOURCE_BYTES = 6,
  WAFER_SPM_REQ_SLOT_BYTES = 7,
  WAFER_SPM_REQ_GUARD = 15,
};

enum WaferSPMRecordWord {
  WAFER_SPM_REC_MAGIC = 0,
  WAFER_SPM_REC_SCHEMA_AND_WORDS = 1,
  WAFER_SPM_REC_STATUS = 2,
  WAFER_SPM_REC_CASE = 3,
  WAFER_SPM_REC_ADDRESS = 4,
  WAFER_SPM_REC_TRANSFER_BYTES = 5,
  WAFER_SPM_REC_SAMPLE = 6,
  WAFER_SPM_REC_REQUEST_GUARD = 7,
  WAFER_SPM_REC_OUTPUT_DDR_OFFSET = 8,
  WAFER_SPM_REC_SLOT_BYTES = 9,
  WAFER_SPM_REC_SPM_GUARD_MISMATCHES = 10,
  WAFER_SPM_REC_RDMA_INST_DELTA = 11,
  WAFER_SPM_REC_WDMA_INST_DELTA = 12,
  WAFER_SPM_REC_RDMA_EXEC_DELTA = 13,
  WAFER_SPM_REC_WDMA_EXEC_DELTA = 14,
  WAFER_SPM_REC_RDMA_BLOCKING_DELTA = 15,
  WAFER_SPM_REC_WDMA_BLOCKING_DELTA = 16,
  WAFER_SPM_REC_RECORD_GUARD = 31,
};

#endif
