#ifndef WAFER_SPM_SUSTAINED_CONFLICT_PROBE_PROTOCOL_H
#define WAFER_SPM_SUSTAINED_CONFLICT_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_SSC_REQUEST_MAGIC UINT64_C(0x31514353504d5357)
#define WAFER_SSC_RECORD_MAGIC UINT64_C(0x31524353504d5357)
#define WAFER_SSC_ROW_MAGIC UINT64_C(0x31575253504d5357)
#define WAFER_SSC_REQUEST_GUARD UINT64_C(0x6f4a31c9e2b587d0)
#define WAFER_SSC_RECORD_GUARD UINT64_C(0x91d8b42e63ca705f)
#define WAFER_SSC_ROW_RECORD_GUARD UINT64_C(0x38c5e719a46db20f)
#define WAFER_SSC_PORT_RESPONSE_GUARD UINT64_C(0x5a1ce07d93b2468f)
#define WAFER_SSC_CLEANUP_RECORD_GUARD UINT64_C(0xc47a029d6e18b35f)
#define WAFER_SSC_SCHEMA 3U
#define WAFER_SSC_REQUEST_WORDS 36U
#define WAFER_SSC_RECORD_WORDS 32U
#define WAFER_SSC_ROW_RECORD_WORDS 86U
#define WAFER_SSC_ROW_COUNT 4U
#define WAFER_SSC_REPEATS 4U
#define WAFER_SSC_RESOURCE_BYTES 2097152U
#define WAFER_SSC_RESOURCE_CANARY UINT8_C(0xa5)
#define WAFER_SSC_SPM_CANARY UINT8_C(0x6d)

#define WAFER_SSC_TRANSFER_BYTES 4096U
#define WAFER_SSC_SPM_BASE UINT64_C(0x80000)
#define WAFER_SSC_SPM_CELL_STRIDE UINT64_C(0x8000)
#define WAFER_SSC_SPM_READ0_OFFSET UINT64_C(0x100)
#define WAFER_SSC_SPM_READ1_OFFSET UINT64_C(0x2100)
#define WAFER_SSC_SPM_WRITE_OFFSET UINT64_C(0x4100)
#define WAFER_SSC_CANDIDATE_OFFSET UINT64_C(8192)
#define WAFER_SSC_CONTROL_OFFSET UINT64_C(4352)

#define WAFER_SSC_PAYLOAD_READ0_OFFSET UINT64_C(0x10000)
#define WAFER_SSC_PAYLOAD_READ1_OFFSET UINT64_C(0x20000)
#define WAFER_SSC_PAYLOAD_RDMA_OFFSET UINT64_C(0x30000)
#define WAFER_SSC_PAYLOAD_CANARY_OFFSET UINT64_C(0x50000)
#define WAFER_SSC_PAYLOAD_CANARY_BYTES UINT64_C(65536)
#define WAFER_SSC_OUTPUT_ARCHIVE_BASE UINT64_C(0x10000)
#define WAFER_SSC_OUTPUT_ARCHIVE_STRIDE UINT64_C(0x20000)
#define WAFER_SSC_PORT_RESPONSE_BASE UINT64_C(0x100000)
#define WAFER_SSC_PORT_RESPONSE_STRIDE UINT64_C(0x10000)
#define WAFER_SSC_ROW_RECORD_BASE_WORD WAFER_SSC_RECORD_WORDS

#define WAFER_SSC_SPM_PORT_PMU_BASE UINT64_C(0x580000)
#define WAFER_SSC_SPM_PORT_PMU_REQUIRED_ENABLE UINT32_C(0x1f)
#define WAFER_SSC_SPM_PORT_PMU_STABLE_MASK UINT32_C(0xf)

enum WaferSSCPortPmuScopeFlag {
  WAFER_SSC_PORT_SCOPE_BEFORE_STABLE = UINT32_C(1) << 0,
  WAFER_SSC_PORT_SCOPE_BOUNDARY_STABLE = UINT32_C(1) << 1,
  WAFER_SSC_PORT_SCOPE_AFTER_STABLE = UINT32_C(1) << 2,
  WAFER_SSC_PORT_SCOPE_WINDOW_UNCHANGED = UINT32_C(1) << 3,
  WAFER_SSC_PORT_SCOPE_RESTORED = UINT32_C(1) << 4,
};

#define WAFER_SSC_SPM_PORT_PMU_SCOPE_MASK                         \
  (WAFER_SSC_PORT_SCOPE_BEFORE_STABLE |                           \
   WAFER_SSC_PORT_SCOPE_BOUNDARY_STABLE |                         \
   WAFER_SSC_PORT_SCOPE_AFTER_STABLE |                            \
   WAFER_SSC_PORT_SCOPE_WINDOW_UNCHANGED |                        \
   WAFER_SSC_PORT_SCOPE_RESTORED)

enum WaferSSCStatus {
  WAFER_SSC_STATUS_OK = 0,
  WAFER_SSC_STATUS_BAD_REQUEST = 1,
  WAFER_SSC_STATUS_PREPARE_FAILED = 2,
  WAFER_SSC_STATUS_EXECUTE_FAILED = 3,
  WAFER_SSC_STATUS_READBACK_FAILED = 4,
  WAFER_SSC_STATUS_PMU_SCOPE_FAILED = 5,
  WAFER_SSC_STATUS_CLEANUP_FAILED = 6,
};

enum WaferSSCCleanupPhase {
  WAFER_SSC_CLEANUP_SETUP = UINT32_C(1) << 0,
  WAFER_SSC_CLEANUP_MEASURED_PAIR = UINT32_C(1) << 1,
  WAFER_SSC_CLEANUP_MATCHED_WDMA = UINT32_C(1) << 2,
  WAFER_SSC_CLEANUP_ARCHIVE = UINT32_C(1) << 3,
};

enum WaferSSCFlag {
  WAFER_SSC_FLAG_PREPARED = UINT32_C(1) << 0,
  WAFER_SSC_FLAG_ISSUED = UINT32_C(1) << 1,
  WAFER_SSC_FLAG_COMPLETED = UINT32_C(1) << 2,
  WAFER_SSC_FLAG_PMU_RECORDED = UINT32_C(1) << 3,
  WAFER_SSC_FLAG_READBACK = UINT32_C(1) << 4,
  WAFER_SSC_FLAG_EXACT_OWNED_RANGE = UINT32_C(1) << 5,
  WAFER_SSC_FLAG_PORT_PMU_RECORDED = UINT32_C(1) << 6,
  WAFER_SSC_FLAG_PORT_MATCHED_READBACK = UINT32_C(1) << 7,
  WAFER_SSC_FLAG_PORT_ENABLE_RESTORED = UINT32_C(1) << 8,
  WAFER_SSC_FLAG_CLEANUP_EVIDENCE = UINT32_C(1) << 9,
};

#define WAFER_SSC_REQUIRED_FLAGS                                     \
  (WAFER_SSC_FLAG_PREPARED | WAFER_SSC_FLAG_ISSUED |               \
   WAFER_SSC_FLAG_COMPLETED | WAFER_SSC_FLAG_PMU_RECORDED |        \
   WAFER_SSC_FLAG_READBACK | WAFER_SSC_FLAG_EXACT_OWNED_RANGE |    \
   WAFER_SSC_FLAG_PORT_PMU_RECORDED |                              \
   WAFER_SSC_FLAG_PORT_MATCHED_READBACK |                          \
   WAFER_SSC_FLAG_PORT_ENABLE_RESTORED |                            \
   WAFER_SSC_FLAG_CLEANUP_EVIDENCE)

enum WaferSSCRequestWord {
  WAFER_SSC_REQ_MAGIC = 0,
  WAFER_SSC_REQ_SCHEMA_AND_WORDS = 1,
  WAFER_SSC_REQ_GROUP = 2,
  WAFER_SSC_REQ_WORK_BYTES = 3,
  WAFER_SSC_REQ_ROUNDS = 4,
  WAFER_SSC_REQ_ISSUE_ORDER = 5,
  WAFER_SSC_REQ_SAMPLE = 6,
  WAFER_SSC_REQ_REPEATS = 7,
  WAFER_SSC_REQ_ROWS = 8,
  WAFER_SSC_REQ_TRANSFER_BYTES = 9,
  WAFER_SSC_REQ_SPM_BASE = 10,
  WAFER_SSC_REQ_SPM_CELL_STRIDE = 11,
  WAFER_SSC_REQ_SPM_READ0_OFFSET = 12,
  WAFER_SSC_REQ_SPM_READ1_OFFSET = 13,
  WAFER_SSC_REQ_SPM_WRITE_OFFSET = 14,
  WAFER_SSC_REQ_CANDIDATE_OFFSET = 15,
  WAFER_SSC_REQ_CONTROL_OFFSET = 16,
  WAFER_SSC_REQ_OWNED_SPM_BYTES = 17,
  WAFER_SSC_REQ_RESOURCE_BYTES = 18,
  WAFER_SSC_REQ_PAYLOAD_READ0_OFFSET = 19,
  WAFER_SSC_REQ_PAYLOAD_READ1_OFFSET = 20,
  WAFER_SSC_REQ_PAYLOAD_RDMA_OFFSET = 21,
  WAFER_SSC_REQ_PAYLOAD_CANARY_OFFSET = 22,
  WAFER_SSC_REQ_PAYLOAD_CANARY_BYTES = 23,
  WAFER_SSC_REQ_OUTPUT_ARCHIVE_BASE = 24,
  WAFER_SSC_REQ_OUTPUT_ARCHIVE_STRIDE = 25,
  WAFER_SSC_REQ_ROW_RECORD_BASE_WORD = 26,
  WAFER_SSC_REQ_ROW_RECORD_WORDS = 27,
  WAFER_SSC_REQ_RESOURCE_CANARY = 28,
  WAFER_SSC_REQ_SPM_CANARY = 29,
  WAFER_SSC_REQ_GUARD = 30,
  WAFER_SSC_REQ_PORT_RESPONSE_BASE = 31,
  WAFER_SSC_REQ_PORT_RESPONSE_STRIDE = 32,
  WAFER_SSC_REQ_SPM_PORT_PMU_BASE = 33,
  WAFER_SSC_REQ_SPM_PORT_PMU_REQUIRED_ENABLE = 34,
  WAFER_SSC_REQ_RESERVED = 35,
};

enum WaferSSCRecordWord {
  WAFER_SSC_REC_MAGIC = 0,
  WAFER_SSC_REC_SCHEMA_AND_WORDS = 1,
  WAFER_SSC_REC_STATUS = 2,
  WAFER_SSC_REC_GROUP = 3,
  WAFER_SSC_REC_WORK_BYTES = 4,
  WAFER_SSC_REC_ROUNDS = 5,
  WAFER_SSC_REC_ISSUE_ORDER = 6,
  WAFER_SSC_REC_SAMPLE = 7,
  WAFER_SSC_REC_ROWS = 8,
  WAFER_SSC_REC_COMPLETED_ROWS = 9,
  WAFER_SSC_REC_TRANSFER_BYTES = 10,
  WAFER_SSC_REC_SPM_BASE = 11,
  WAFER_SSC_REC_OWNED_SPM_BYTES = 12,
  WAFER_SSC_REC_REQUEST_DDR = 13,
  WAFER_SSC_REC_PAYLOAD_DDR = 14,
  WAFER_SSC_REC_OUTPUT_DDR = 15,
  WAFER_SSC_REC_EXECUTION_ROTATION = 16,
  WAFER_SSC_REC_FLAGS = 17,
  WAFER_SSC_REC_REQUEST_GUARD = 18,
  WAFER_SSC_REC_RECORD_GUARD = 19,
};

enum WaferSSCRowRecordWord {
  WAFER_SSC_ROW_MAGIC_WORD = 0,
  WAFER_SSC_ROW_SCHEMA_AND_WORDS = 1,
  WAFER_SSC_ROW_STATUS = 2,
  WAFER_SSC_ROW_CELL = 3,
  WAFER_SSC_ROW_ADDRESS_CLASS = 4,
  WAFER_SSC_ROW_RELATIVE_OFFSET = 5,
  WAFER_SSC_ROW_SCHEDULE = 6,
  WAFER_SSC_ROW_ISSUE_ORDER = 7,
  WAFER_SSC_ROW_SAMPLE = 8,
  WAFER_SSC_ROW_EXECUTION_ORDINAL = 9,
  WAFER_SSC_ROW_ROUNDS = 10,
  WAFER_SSC_ROW_TRANSFER_BYTES = 11,
  WAFER_SSC_ROW_SPM_BASE = 12,
  WAFER_SSC_ROW_OWNED_SPM_BYTES = 13,
  WAFER_SSC_ROW_SPM_CELL_STRIDE = 14,
  WAFER_SSC_ROW_SPM_READ0_OFFSET = 15,
  WAFER_SSC_ROW_SPM_READ1_OFFSET = 16,
  WAFER_SSC_ROW_SPM_WRITE_OFFSET = 17,
  WAFER_SSC_ROW_RDMA_WRITE_OFFSET = 18,
  WAFER_SSC_ROW_ARCHIVE_OFFSET = 19,
  WAFER_SSC_ROW_REQUEST_DDR = 20,
  WAFER_SSC_ROW_PAYLOAD_DDR = 21,
  WAFER_SSC_ROW_OUTPUT_DDR = 22,
  WAFER_SSC_ROW_CT_INST_DELTA = 23,
  WAFER_SSC_ROW_RDMA_INST_DELTA = 24,
  WAFER_SSC_ROW_OTHER_INST_DELTA = 25,
  WAFER_SSC_ROW_WORKER_CT_INST_DELTA = 26,
  WAFER_SSC_ROW_WORKER_RDMA_INST_DELTA = 27,
  WAFER_SSC_ROW_CT_EXEC_DELTA = 28,
  WAFER_SSC_ROW_RDMA_EXEC_DELTA = 29,
  WAFER_SSC_ROW_FULL_EXEC_DELTA = 30,
  WAFER_SSC_ROW_CT_BLOCKING_DELTA = 31,
  WAFER_SSC_ROW_RDMA_BLOCKING_DELTA = 32,
  WAFER_SSC_ROW_PLAN_CYCLES = 33,
  WAFER_SSC_ROW_PMU_ENABLE = 34,
  WAFER_SSC_ROW_SERIAL_MODE = 35,
  WAFER_SSC_ROW_STABLE_BEFORE = 36,
  WAFER_SSC_ROW_STABLE_AFTER = 37,
  WAFER_SSC_ROW_FINAL_CONTROL = 38,
  WAFER_SSC_ROW_FLAGS = 39,
  WAFER_SSC_ROW_REQUEST_GUARD = 40,
  WAFER_SSC_ROW_GUARD_WORD = 41,
  WAFER_SSC_ROW_SPM_PORT_PMU_BASE = 42,
  WAFER_SSC_ROW_SPM_PORT_PMU_REQUIRED_ENABLE = 43,
  WAFER_SSC_ROW_SPM_PORT_PMU_ENABLE_ORIGINAL = 44,
  WAFER_SSC_ROW_SPM_PORT_PMU_ENABLE_BEFORE = 45,
  WAFER_SSC_ROW_SPM_PORT_PMU_ENABLE_BOUNDARY = 46,
  WAFER_SSC_ROW_SPM_PORT_PMU_ENABLE_AFTER = 47,
  WAFER_SSC_ROW_SPM_PORT_PMU_ENABLE_RESTORED = 48,
  WAFER_SSC_ROW_SPM_PORT_PMU_STABLE_BEFORE = 49,
  WAFER_SSC_ROW_SPM_PORT_PMU_STABLE_BOUNDARY = 50,
  WAFER_SSC_ROW_SPM_PORT_PMU_STABLE_AFTER = 51,
  WAFER_SSC_ROW_SPM_PORT0_T2_BEFORE = 52,
  WAFER_SSC_ROW_SPM_PORT0_T2_BOUNDARY = 53,
  WAFER_SSC_ROW_SPM_PORT0_T2_AFTER = 54,
  WAFER_SSC_ROW_SPM_PORT0_T3_BEFORE = 55,
  WAFER_SSC_ROW_SPM_PORT0_T3_BOUNDARY = 56,
  WAFER_SSC_ROW_SPM_PORT0_T3_AFTER = 57,
  WAFER_SSC_ROW_SPM_PORT6_T2_BEFORE = 58,
  WAFER_SSC_ROW_SPM_PORT6_T2_BOUNDARY = 59,
  WAFER_SSC_ROW_SPM_PORT6_T2_AFTER = 60,
  WAFER_SSC_ROW_SPM_PORT6_T3_BEFORE = 61,
  WAFER_SSC_ROW_SPM_PORT6_T3_BOUNDARY = 62,
  WAFER_SSC_ROW_SPM_PORT6_T3_AFTER = 63,
  WAFER_SSC_ROW_WDMA_INST_DELTA = 64,
  WAFER_SSC_ROW_WDMA_OTHER_INST_DELTA = 65,
  WAFER_SSC_ROW_WORKER_WDMA_INST_DELTA = 66,
  WAFER_SSC_ROW_WDMA_FINAL_CONTROL = 67,
  WAFER_SSC_ROW_PORT_READBACK_OFFSET = 68,
  WAFER_SSC_ROW_PORT_READBACK_BYTES = 69,
  WAFER_SSC_ROW_SPM_PORT_PMU_SCOPE_FLAGS = 70,
  WAFER_SSC_ROW_PORT_RESPONSE_GUARD = 71,
  WAFER_SSC_ROW_SETUP_ACCEPTED = 72,
  WAFER_SSC_ROW_SETUP_PENDING_AFTER = 73,
  WAFER_SSC_ROW_SETUP_FINAL_CONTROL = 74,
  WAFER_SSC_ROW_MEASURED_PAIR_ACCEPTED = 75,
  WAFER_SSC_ROW_MEASURED_PAIR_PENDING_AFTER = 76,
  WAFER_SSC_ROW_MATCHED_WDMA_ACCEPTED = 77,
  WAFER_SSC_ROW_MATCHED_WDMA_PENDING_AFTER = 78,
  WAFER_SSC_ROW_ARCHIVE_ACCEPTED = 79,
  WAFER_SSC_ROW_ARCHIVE_PENDING_AFTER = 80,
  WAFER_SSC_ROW_ARCHIVE_FINAL_CONTROL = 81,
  WAFER_SSC_ROW_CLEANUP_ATTEMPTED_MASK = 82,
  WAFER_SSC_ROW_CLEANUP_SUCCEEDED_MASK = 83,
  WAFER_SSC_ROW_POISONED_PHASE_MASK = 84,
  WAFER_SSC_ROW_CLEANUP_RECORD_GUARD = 85,
};

#endif
