#ifndef WAFER_WORKER_PLACEMENT_PROBE_PROTOCOL_H
#define WAFER_WORKER_PLACEMENT_PROBE_PROTOCOL_H

#include <stdint.h>

/*
 * Wire contract for rank-one worker placement/progress characterization.
 *
 * The contract intentionally exposes only observations available from the
 * current target: one common device-cycle window, per-worker instruction and
 * blocking counters, worker task-done controls, and exact guarded results.
 * It does not invent a per-worker completion timestamp or an arbiter policy.
 */

#define WAFER_WP_REQUEST_MAGIC UINT64_C(0x3151455250574657)
#define WAFER_WP_RECORD_MAGIC UINT64_C(0x3143455250574657)
#define WAFER_WP_REQUEST_GUARD UINT64_C(0x8a6d51c307be24f9)
#define WAFER_WP_RECORD_GUARD UINT64_C(0xe41b97c2605da83f)
#define WAFER_WP_SCHEMA 1U
#define WAFER_WP_REQUEST_WORDS 24U
#define WAFER_WP_RECORD_WORDS 192U
#define WAFER_WP_WORKERS 3U
#define WAFER_WP_QUEUES 5U
#define WAFER_WP_PMU64_COUNTERS 8U
#define WAFER_WP_MAX_ISSUES 6U
#define WAFER_WP_PLACEMENT_ISSUES 6U
#define WAFER_WP_BACKLOG_ISSUES 4U
#define WAFER_WP_PLACEMENT_BYTES 16384U
#define WAFER_WP_RDMA_BACKLOG_BYTES 65536U
#define WAFER_WP_NE_RESULT_BYTES 16384U
#define WAFER_WP_SENTINEL_BYTES 4096U
#define WAFER_WP_GUARD_BYTES 256U
#define WAFER_WP_OUTPUT_SLOT_BASE 4096U
#define WAFER_WP_OUTPUT_SLOT_DATA_BYTES 65536U
#define WAFER_WP_OUTPUT_SLOT_STRIDE                                      \
  (WAFER_WP_OUTPUT_SLOT_DATA_BYTES + 2U * WAFER_WP_GUARD_BYTES)
#define WAFER_WP_RESOURCE_BYTES                                          \
  (WAFER_WP_OUTPUT_SLOT_BASE +                                          \
   WAFER_WP_MAX_ISSUES * WAFER_WP_OUTPUT_SLOT_STRIDE)
#define WAFER_WP_SPM_SLOT_BASE UINT64_C(0x10000)
#define WAFER_WP_SPM_SLOT_STRIDE UINT64_C(0x40000)
#define WAFER_WP_SPM_READ0_OFFSET UINT64_C(0x100)
#define WAFER_WP_SPM_READ1_OFFSET UINT64_C(0x11000)
#define WAFER_WP_SPM_WRITE_OFFSET UINT64_C(0x21000)

enum WaferWPCaseKind {
  WAFER_WP_KIND_PLACEMENT = 0,
  WAFER_WP_KIND_BACKLOG_ONLY = 1,
  WAFER_WP_KIND_SENTINEL_ONLY = 2,
  WAFER_WP_KIND_CONCURRENT = 3,
};

enum WaferWPEngine {
  WAFER_WP_ENGINE_CT = 0,
  WAFER_WP_ENGINE_NE = 1,
  WAFER_WP_ENGINE_RDMA = 2,
};

enum WaferWPStatus {
  WAFER_WP_STATUS_OK = 0,
  WAFER_WP_STATUS_BAD_REQUEST = 1,
  WAFER_WP_STATUS_PREPARE_FAILED = 2,
  WAFER_WP_STATUS_ISSUE_FAILED = 3,
  WAFER_WP_STATUS_WAIT_FAILED = 4,
  WAFER_WP_STATUS_ORACLE_FAILED = 5,
};

enum WaferWPRecordFlag {
  WAFER_WP_RECORD_BEFORE_CAPTURED = UINT32_C(1) << 0,
  WAFER_WP_RECORD_ISSUES_SUBMITTED = UINT32_C(1) << 1,
  WAFER_WP_RECORD_BOUNDARY_CAPTURED = UINT32_C(1) << 2,
  WAFER_WP_RECORD_SAFETY_DRAINED = UINT32_C(1) << 3,
  WAFER_WP_RECORD_FINAL_CAPTURED = UINT32_C(1) << 4,
  WAFER_WP_RECORD_OUTPUT_ARCHIVED = UINT32_C(1) << 5,
};

enum WaferWPRequestWord {
  WAFER_WP_REQ_MAGIC = 0,
  WAFER_WP_REQ_SCHEMA_AND_WORDS = 1,
  WAFER_WP_REQ_KIND = 2,
  WAFER_WP_REQ_ENGINE = 3,
  WAFER_WP_REQ_WORKER_MASK = 4,
  WAFER_WP_REQ_TARGET_WORKER = 5,
  WAFER_WP_REQ_OBSERVER_WORKER = 6,
  WAFER_WP_REQ_SAMPLE = 7,
  WAFER_WP_REQ_WORKER0_ISSUES = 8,
  WAFER_WP_REQ_WORKER1_ISSUES = 9,
  WAFER_WP_REQ_WORKER2_ISSUES = 10,
  WAFER_WP_REQ_PRIMARY_BYTES = 11,
  WAFER_WP_REQ_SENTINEL_BYTES = 12,
  WAFER_WP_REQ_ISSUE_ROTATION = 13,
  WAFER_WP_REQ_JOIN_ROTATION = 14,
  WAFER_WP_REQ_RESOURCE_BYTES = 15,
  WAFER_WP_REQ_GUARD = 16,
  WAFER_WP_REQ_RESERVED_BASE = 17,
};

enum WaferWPRecordWord {
  WAFER_WP_REC_MAGIC = 0,
  WAFER_WP_REC_SCHEMA_AND_WORDS = 1,
  WAFER_WP_REC_STATUS = 2,
  WAFER_WP_REC_FLAGS = 3,
  WAFER_WP_REC_KIND = 4,
  WAFER_WP_REC_ENGINE = 5,
  WAFER_WP_REC_WORKER_MASK = 6,
  WAFER_WP_REC_TARGET_WORKER = 7,
  WAFER_WP_REC_OBSERVER_WORKER = 8,
  WAFER_WP_REC_SAMPLE = 9,
  WAFER_WP_REC_ISSUE_COUNT = 10,
  WAFER_WP_REC_PRIMARY_BYTES = 11,
  WAFER_WP_REC_SENTINEL_BYTES = 12,
  WAFER_WP_REC_REQUEST_GUARD = 13,
  WAFER_WP_REC_RECORD_GUARD = 14,
  WAFER_WP_REC_RESOURCE_BYTES = 15,
  WAFER_WP_REC_OUTPUT_SLOT_BASE = 16,
  WAFER_WP_REC_OUTPUT_SLOT_STRIDE = 17,
  WAFER_WP_REC_OUTPUT_GUARD_BYTES = 18,
  WAFER_WP_REC_PMU_ENABLE = 19,
  WAFER_WP_REC_STABLE_BEFORE = 20,
  WAFER_WP_REC_STABLE_AFTER = 21,
  WAFER_WP_REC_START_CYCLE = 22,
  WAFER_WP_REC_AFTER_ISSUE_CYCLE = 23,
  WAFER_WP_REC_OBSERVER_BOUNDARY_CYCLE = 24,
  WAFER_WP_REC_FINAL_CYCLE = 25,
  WAFER_WP_REC_OBSERVER_WAIT_CYCLES = 26,
  WAFER_WP_REC_TARGET_WAIT_CYCLES = 27,
  WAFER_WP_REC_TARGET_PENDING_BOUNDARY = 28,
  WAFER_WP_REC_OBSERVER_DONE_BOUNDARY = 29,
  WAFER_WP_REC_BOUNDARY_MISMATCHES = 30,
  WAFER_WP_REC_FINAL_MISMATCHES = 31,
  WAFER_WP_REC_FINAL_GUARD_MISMATCHES = 32,
  WAFER_WP_REC_ISSUE_WORKER_BASE = 33,
  WAFER_WP_REC_ISSUE_ENGINE_BASE = 39,
  WAFER_WP_REC_ISSUE_BYTES_BASE = 45,
  WAFER_WP_REC_ISSUE_RC_BASE = 51,
  WAFER_WP_REC_ISSUE_INTER_TYPE_BASE = 57,
  WAFER_WP_REC_CONTROL_AFTER_ISSUE = 63,
  WAFER_WP_REC_CONTROL_BOUNDARY = 66,
  WAFER_WP_REC_CONTROL_FINAL = 69,
  WAFER_WP_REC_JOIN_CYCLE_BASE = 72,
  WAFER_WP_REC_PMU64_BEFORE = 75,
  WAFER_WP_REC_PMU64_AFTER = 83,
  WAFER_WP_REC_INSTRUCTION_BEFORE = 91,
  WAFER_WP_REC_INSTRUCTION_AFTER = 106,
  WAFER_WP_REC_BLOCKING_BEFORE = 121,
  WAFER_WP_REC_BLOCKING_AFTER = 136,
  WAFER_WP_REC_OUTPUT_BYTES_BASE = 151,
  WAFER_WP_REC_OUTPUT_OFFSET_BASE = 157,
  WAFER_WP_REC_SLOT_MISMATCH_BASE = 163,
  WAFER_WP_REC_SLOT_GUARD_MISMATCH_BASE = 169,
  WAFER_WP_REC_SERIAL_MODE_BASE = 175,
};

#endif
