#ifndef WAFER_CT_VUVLOOP_SEMANTICS_PROTOCOL_H
#define WAFER_CT_VUVLOOP_SEMANTICS_PROTOCOL_H

#include <stdint.h>

/*
 * This isolated protocol dispatches only supported VuVLoop controls:
 * unit_elem_count is exactly 64 and the base/full count ratios match.
 * Out-of-contract geometries remain host-only verifier negatives.
 *
 * Every valid invocation is NCC-only: whole-slot RDMA seeds for lhs, rhs and
 * output, one CT attempt, one whole-slot WDMA capture, and one terminal local
 * fence.  The probe never accesses SPM from Kcore.
 */
#define WAFER_CTVL_REQUEST_MAGIC UINT64_C(0x31514552564c5657)
#define WAFER_CTVL_RECORD_MAGIC UINT64_C(0x31434552564c5657)
#define WAFER_CTVL_SCHEMA 1U
#define WAFER_CTVL_REQUEST_WORDS 16U
#define WAFER_CTVL_RECORD_WORDS 24U
#define WAFER_CTVL_CASE_BASE 20000U
#define WAFER_CTVL_OPCODE 17U
#define WAFER_CTVL_DTYPE 0U
#define WAFER_CTVL_ELEMENT_BYTES 2U
#define WAFER_CTVL_PHYSICAL_BLOCK_BYTES 256U
#define WAFER_CTVL_RESOURCE_BYTES 8192U
#define WAFER_CTVL_LHS_OWNED_BYTES 1024U
#define WAFER_CTVL_RHS_OWNED_BYTES 512U
#define WAFER_CTVL_OUTPUT_CAPTURE_BYTES 1024U
#define WAFER_CTVL_GUARD_BYTES 256U
#define WAFER_CTVL_GUARD_BYTE UINT8_C(0xa7)
#define WAFER_CTVL_REQUEST_PADDING_BYTE UINT8_C(0xc9)
#define WAFER_CTVL_REQUEST_GUARD UINT64_C(0xc14d2e3f50617283)
#define WAFER_CTVL_RECORD_GUARD UINT64_C(0x8a79685746352413)

#define WAFER_CTVL_LHS_SLOT_BYTES 1536U
#define WAFER_CTVL_RHS_SLOT_BYTES 1024U
#define WAFER_CTVL_OUTPUT_SLOT_BYTES 1536U
#define WAFER_CTVL_PAYLOAD_LHS_OFFSET 0U
#define WAFER_CTVL_PAYLOAD_RHS_OFFSET 1536U
#define WAFER_CTVL_PAYLOAD_OUTPUT_SEED_OFFSET 2560U
#define WAFER_CTVL_RECORD_RESERVED_BYTES 512U
#define WAFER_CTVL_OUTPUT_DDR_OFFSET 512U
#define WAFER_CTVL_BODY_OFFSET 256U

#define WAFER_CTVL_SPM_LHS UINT64_C(0x10000)
#define WAFER_CTVL_SPM_RHS UINT64_C(0x30000)
#define WAFER_CTVL_SPM_OUTPUT UINT64_C(0x50000)

enum WaferCTVLDisposition {
  WAFER_CTVL_EXACT_CONTROL = 0,
  WAFER_CTVL_BOUNDED_OBSERVATION = 1,
};

enum WaferCTVLCase {
  WAFER_CTVL_RECTANGULAR_CONTROL = WAFER_CTVL_CASE_BASE,
  WAFER_CTVL_SUPPORTED_OUTER2_CONTROL,
};

enum WaferCTVLStatus {
  WAFER_CTVL_STATUS_OK = 0,
  WAFER_CTVL_STATUS_BAD_REQUEST = 1,
  WAFER_CTVL_STATUS_UNSUPPORTED_CASE = 2,
  WAFER_CTVL_STATUS_EXECUTE_REJECTED = 3,
};

enum WaferCTVLRequestWord {
  WAFER_CTVL_REQ_MAGIC = 0,
  WAFER_CTVL_REQ_SCHEMA_AND_WORDS = 1,
  WAFER_CTVL_REQ_CASE = 2,
  WAFER_CTVL_REQ_DISPOSITION = 3,
  WAFER_CTVL_REQ_OPCODE = 4,
  WAFER_CTVL_REQ_DTYPE = 5,
  WAFER_CTVL_REQ_ELEM_COUNT = 6,
  WAFER_CTVL_REQ_UNIT_ELEM_COUNT = 7,
  WAFER_CTVL_REQ_FULL_ELEM_COUNT = 8,
  WAFER_CTVL_REQ_FULL_UNIT_ELEM_COUNT = 9,
  WAFER_CTVL_REQ_LHS_OWNED_BYTES = 10,
  WAFER_CTVL_REQ_RHS_OWNED_BYTES = 11,
  WAFER_CTVL_REQ_OUTPUT_CAPTURE_BYTES = 12,
  WAFER_CTVL_REQ_GUARD_BYTES = 13,
  WAFER_CTVL_REQ_SAMPLE = 14,
  WAFER_CTVL_REQ_GUARD = 15,
};

enum WaferCTVLRecordWord {
  WAFER_CTVL_REC_MAGIC = 0,
  WAFER_CTVL_REC_SCHEMA_AND_WORDS = 1,
  WAFER_CTVL_REC_STATUS = 2,
  WAFER_CTVL_REC_CASE = 3,
  WAFER_CTVL_REC_DISPOSITION = 4,
  WAFER_CTVL_REC_OPCODE = 5,
  WAFER_CTVL_REC_DTYPE = 6,
  WAFER_CTVL_REC_ELEM_COUNT = 7,
  WAFER_CTVL_REC_UNIT_ELEM_COUNT = 8,
  WAFER_CTVL_REC_FULL_ELEM_COUNT = 9,
  WAFER_CTVL_REC_FULL_UNIT_ELEM_COUNT = 10,
  WAFER_CTVL_REC_EXECUTE_RESULT = 11,
  WAFER_CTVL_REC_COMPLETION_SEEN = 12,
  WAFER_CTVL_REC_REQUEST_ECHO_MISMATCHES = 13,
  WAFER_CTVL_REC_SAMPLE = 14,
  WAFER_CTVL_REC_REQUEST_GUARD = 15,
  WAFER_CTVL_REC_OUTPUT_DDR_OFFSET = 16,
  WAFER_CTVL_REC_OUTPUT_SLOT_BYTES = 17,
  WAFER_CTVL_REC_BODY_OFFSET = 18,
  WAFER_CTVL_REC_OUTPUT_OWNED_BYTES = 19,
  WAFER_CTVL_REC_OUTPUT_PHYSICAL_SPAN = 20,
  WAFER_CTVL_REC_RESOURCE_BYTES = 21,
  WAFER_CTVL_REC_TERMINAL_FENCE_COUNT = 22,
  WAFER_CTVL_REC_RECORD_GUARD = 23,
};

#endif
