#ifndef WAFER_DDR_TILE_OFFSET_PROBE_PROTOCOL_H
#define WAFER_DDR_TILE_OFFSET_PROBE_PROTOCOL_H

#include <stdint.h>

#define WAFER_DDR_TILE_REQUEST_MAGIC UINT64_C(0x5744445254494c45)
#define WAFER_DDR_TILE_RECORD_MAGIC UINT64_C(0x5744445252454344)
#define WAFER_DDR_TILE_ROW_MAGIC UINT64_C(0x57444452524f5721)
#define WAFER_DDR_TILE_REQUEST_GUARD UINT64_C(0x8c21a549f0e36db7)
#define WAFER_DDR_TILE_RECORD_GUARD UINT64_C(0xb41ef09c7263d85a)
#define WAFER_DDR_TILE_ROW_GUARD UINT64_C(0x6d9703f1ca4285be)
#define WAFER_DDR_TILE_CONFLICT_ROW_MAGIC UINT64_C(0x5744445243464c54)
#define WAFER_DDR_TILE_CONFLICT_ROW_GUARD UINT64_C(0x71a5ce29b406df83)
#define WAFER_DDR_TILE_SCHEMA 3U

#define WAFER_DDR_TILE_RANKS 16U
#define WAFER_DDR_TILE_ALLOCATIONS 2U
#define WAFER_DDR_TILE_OFFSET_COUNT 14U
#define WAFER_DDR_TILE_DIRECTIONS 2U
#define WAFER_DDR_TILE_SAMPLES 3U
#define WAFER_DDR_TILE_ROWS                                                    \
  (WAFER_DDR_TILE_ALLOCATIONS * WAFER_DDR_TILE_OFFSET_COUNT *                  \
   WAFER_DDR_TILE_DIRECTIONS * WAFER_DDR_TILE_SAMPLES)

#define WAFER_DDR_TILE_RESOURCE_BYTES UINT32_C(0x200000)
#define WAFER_DDR_TILE_PAYLOAD_BYTES UINT32_C(256)
#define WAFER_DDR_TILE_GUARD_BYTES UINT32_C(256)
#define WAFER_DDR_TILE_SLOT_BYTES                                              \
  (WAFER_DDR_TILE_PAYLOAD_BYTES + 2U * WAFER_DDR_TILE_GUARD_BYTES)
#define WAFER_DDR_TILE_CANARY UINT8_C(0xc3)
#define WAFER_DDR_TILE_CANARY_SOURCE_OFFSET UINT32_C(0x2000)
#define WAFER_DDR_TILE_ARCHIVE_BASE UINT32_C(0x10000)
#define WAFER_DDR_TILE_SWEEP_BASE UINT32_C(0x80000)

#define WAFER_DDR_TILE_SPM_GUARDED UINT64_C(0x10000)
#define WAFER_DDR_TILE_SPM_PAYLOAD UINT64_C(0x20000)
#define WAFER_DDR_TILE_SPM_READBACK UINT64_C(0x30000)

/*
 * Conflict-equivalence rows are deliberately a held-out observation suite:
 * every row measures exactly two RDMA instructions between its PMU snapshots.
 * Slot seeding, result archive and their matching fences remain outside that
 * interval.
 */
#define WAFER_DDR_TILE_CONFLICT_BASE_COUNT 2U
#define WAFER_DDR_TILE_CONFLICT_OFFSET_COUNT 3U
#define WAFER_DDR_TILE_CONFLICT_TRANSFER_COUNT 2U
#define WAFER_DDR_TILE_CONFLICT_ORDER_COUNT 2U
#define WAFER_DDR_TILE_CONFLICT_SCHEDULE_COUNT 2U
#define WAFER_DDR_TILE_CONFLICT_SAMPLES 2U
#define WAFER_DDR_TILE_CONFLICT_ROWS                                           \
  (WAFER_DDR_TILE_ALLOCATIONS * WAFER_DDR_TILE_CONFLICT_BASE_COUNT *           \
   WAFER_DDR_TILE_CONFLICT_OFFSET_COUNT *                                      \
   WAFER_DDR_TILE_CONFLICT_TRANSFER_COUNT *                                    \
   WAFER_DDR_TILE_CONFLICT_ORDER_COUNT *                                       \
   WAFER_DDR_TILE_CONFLICT_SCHEDULE_COUNT * WAFER_DDR_TILE_CONFLICT_SAMPLES)
#define WAFER_DDR_TILE_CONFLICT_PAIR_GAP UINT32_C(0x10000)
#define WAFER_DDR_TILE_CONFLICT_SPM_A UINT64_C(0x10000)
#define WAFER_DDR_TILE_CONFLICT_SPM_B UINT64_C(0x30000)
#define WAFER_DDR_TILE_CONFLICT_SMALL_ARCHIVE_BASE UINT32_C(0x20000)
#define WAFER_DDR_TILE_CONFLICT_LARGE_ARCHIVE_BASE UINT32_C(0x190000)
#define WAFER_DDR_TILE_REQUEST_WORDS 16U
#define WAFER_DDR_TILE_HEADER_WORDS 32U
#define WAFER_DDR_TILE_ROW_WORDS 16U
#define WAFER_DDR_TILE_OFFSET_RECORD_BYTES                                     \
  ((WAFER_DDR_TILE_HEADER_WORDS +                                              \
    WAFER_DDR_TILE_ROWS * WAFER_DDR_TILE_ROW_WORDS) *                          \
   8U)
#define WAFER_DDR_TILE_CONFLICT_ROW_WORDS 25U
#define WAFER_DDR_TILE_CONFLICT_RECORD_BYTES                                   \
  ((WAFER_DDR_TILE_HEADER_WORDS +                                              \
    WAFER_DDR_TILE_CONFLICT_ROWS * WAFER_DDR_TILE_CONFLICT_ROW_WORDS) *        \
   8U)

enum WaferDDRTileStatus {
  WAFER_DDR_TILE_STATUS_OK = 0,
  WAFER_DDR_TILE_STATUS_BAD_REQUEST = 1,
};

enum WaferDDRTileDirection {
  WAFER_DDR_TILE_DIRECTION_RDMA = 1,
  WAFER_DDR_TILE_DIRECTION_WDMA = 2,
};

enum WaferDDRTileMode {
  WAFER_DDR_TILE_MODE_OFFSET = 0,
  WAFER_DDR_TILE_MODE_CONFLICT_EQUIVALENCE = 1,
};

enum WaferDDRTileConflictOrder {
  WAFER_DDR_TILE_CONFLICT_ORDER_A_B = 1,
  WAFER_DDR_TILE_CONFLICT_ORDER_B_A = 2,
};

enum WaferDDRTileConflictSchedule {
  WAFER_DDR_TILE_CONFLICT_SCHEDULE_SERIAL = 1,
  WAFER_DDR_TILE_CONFLICT_SCHEDULE_WINDOW = 2,
};

enum WaferDDRTileConflictRankOrder {
  WAFER_DDR_TILE_CONFLICT_RANK_ORDER_FORWARD = 1,
  WAFER_DDR_TILE_CONFLICT_RANK_ORDER_REVERSE = 2,
};

enum WaferDDRTileRequestWord {
  WAFER_DDR_TILE_REQ_MAGIC = 0,
  WAFER_DDR_TILE_REQ_SCHEMA = 1,
  WAFER_DDR_TILE_REQ_RANK = 2,
  WAFER_DDR_TILE_REQ_SAMPLE = 3,
  WAFER_DDR_TILE_REQ_RESOURCE_BYTES = 4,
  WAFER_DDR_TILE_REQ_PAYLOAD_BYTES = 5,
  WAFER_DDR_TILE_REQ_ALLOCATIONS = 6,
  WAFER_DDR_TILE_REQ_OFFSET_COUNT = 7,
  WAFER_DDR_TILE_REQ_MODE = 8,
  WAFER_DDR_TILE_REQ_CONFLICT_SAMPLES = 9,
  WAFER_DDR_TILE_REQ_CONFLICT_BASE_COUNT = 10,
  WAFER_DDR_TILE_REQ_CONFLICT_OFFSET_COUNT = 11,
  WAFER_DDR_TILE_REQ_CONFLICT_TRANSFER_COUNT = 12,
  WAFER_DDR_TILE_REQ_CONFLICT_ORDER_COUNT = 13,
  WAFER_DDR_TILE_REQ_CONFLICT_SCHEDULE_COUNT = 14,
  WAFER_DDR_TILE_REQ_GUARD = 15,
};

enum WaferDDRTileHeaderWord {
  WAFER_DDR_TILE_HDR_MAGIC = 0,
  WAFER_DDR_TILE_HDR_SCHEMA_AND_WORDS = 1,
  WAFER_DDR_TILE_HDR_STATUS = 2,
  WAFER_DDR_TILE_HDR_RANK = 3,
  WAFER_DDR_TILE_HDR_SAMPLE = 4,
  WAFER_DDR_TILE_HDR_ROW_COUNT = 5,
  WAFER_DDR_TILE_HDR_PAYLOAD_BYTES = 6,
  WAFER_DDR_TILE_HDR_GUARD_BYTES = 7,
  WAFER_DDR_TILE_HDR_INPUT0_BASE = 8,
  WAFER_DDR_TILE_HDR_INPUT1_BASE = 9,
  WAFER_DDR_TILE_HDR_OUTPUT0_BASE = 10,
  WAFER_DDR_TILE_HDR_OUTPUT1_BASE = 11,
  WAFER_DDR_TILE_HDR_REQUEST_GUARD = 12,
  WAFER_DDR_TILE_HDR_MODE = 13,
  WAFER_DDR_TILE_HDR_CONFLICT_ROW_COUNT = 14,
  WAFER_DDR_TILE_HDR_CONFLICT_SAMPLES = 15,
  WAFER_DDR_TILE_HDR_CONFLICT_BASE_COUNT = 16,
  WAFER_DDR_TILE_HDR_CONFLICT_OFFSET_COUNT = 17,
  WAFER_DDR_TILE_HDR_CONFLICT_TRANSFER_COUNT = 18,
  WAFER_DDR_TILE_HDR_CONFLICT_RANK_ORDER = 19,
  WAFER_DDR_TILE_HDR_RECORD_GUARD = 31,
};

enum WaferDDRTileRowWord {
  WAFER_DDR_TILE_ROW_MAGIC_WORD = 0,
  WAFER_DDR_TILE_ROW_IDENTITY = 1,
  WAFER_DDR_TILE_ROW_OFFSET = 2,
  WAFER_DDR_TILE_ROW_INPUT_BASE = 3,
  WAFER_DDR_TILE_ROW_OUTPUT_BASE = 4,
  WAFER_DDR_TILE_ROW_DDR_ADDRESS = 5,
  WAFER_DDR_TILE_ROW_SPM_ADDRESS = 6,
  WAFER_DDR_TILE_ROW_COMPLETION_CYCLES = 7,
  WAFER_DDR_TILE_ROW_INST_DELTA = 8,
  WAFER_DDR_TILE_ROW_BLOCKING_DELTA = 9,
  WAFER_DDR_TILE_ROW_ENGINE_EXEC_DELTA = 10,
  WAFER_DDR_TILE_ROW_FU_EXEC_DELTA = 11,
  WAFER_DDR_TILE_ROW_WINDOW_DELTA = 12,
  WAFER_DDR_TILE_ROW_PAYLOAD_BYTES = 13,
  WAFER_DDR_TILE_ROW_ARCHIVE_OFFSET = 14,
  WAFER_DDR_TILE_ROW_GUARD_WORD = 15,
};

enum WaferDDRTileConflictRowWord {
  WAFER_DDR_TILE_CONFLICT_ROW_MAGIC_WORD = 0,
  WAFER_DDR_TILE_CONFLICT_ROW_IDENTITY = 1,
  WAFER_DDR_TILE_CONFLICT_ROW_OFFSET = 2,
  WAFER_DDR_TILE_CONFLICT_ROW_INPUT_BASE = 3,
  WAFER_DDR_TILE_CONFLICT_ROW_OUTPUT_BASE = 4,
  WAFER_DDR_TILE_CONFLICT_ROW_ADDRESS_A = 5,
  WAFER_DDR_TILE_CONFLICT_ROW_ADDRESS_B = 6,
  WAFER_DDR_TILE_CONFLICT_ROW_SPM_A = 7,
  WAFER_DDR_TILE_CONFLICT_ROW_SPM_B = 8,
  WAFER_DDR_TILE_CONFLICT_ROW_TRANSFER_BYTES = 9,
  WAFER_DDR_TILE_CONFLICT_ROW_ARCHIVE_A = 10,
  WAFER_DDR_TILE_CONFLICT_ROW_ARCHIVE_B = 11,
  WAFER_DDR_TILE_CONFLICT_ROW_COMPLETION_CYCLES = 12,
  WAFER_DDR_TILE_CONFLICT_ROW_INST_DELTA = 13,
  WAFER_DDR_TILE_CONFLICT_ROW_BLOCKING_DELTA = 14,
  WAFER_DDR_TILE_CONFLICT_ROW_ENGINE_EXEC_DELTA = 15,
  WAFER_DDR_TILE_CONFLICT_ROW_FU_EXEC_DELTA = 16,
  WAFER_DDR_TILE_CONFLICT_ROW_WINDOW_DELTA = 17,
  WAFER_DDR_TILE_CONFLICT_ROW_BASE_OFFSET = 18,
  WAFER_DDR_TILE_CONFLICT_ROW_ALLOCATION = 19,
  WAFER_DDR_TILE_CONFLICT_ROW_SCHEDULE = 20,
  WAFER_DDR_TILE_CONFLICT_ROW_ISSUE_ORDER = 21,
  WAFER_DDR_TILE_CONFLICT_ROW_SAMPLE = 22,
  WAFER_DDR_TILE_CONFLICT_ROW_GUARD_WORD = 23,
  WAFER_DDR_TILE_CONFLICT_ROW_SCHEDULE_POSITION = 24,
};

#endif
