#ifndef WAFER_NCC_PROBE_PROTOCOL_H
#define WAFER_NCC_PROBE_PROTOCOL_H

#include <stdint.h>

/*
 * Wire protocol for the bounded NCC execution probe.
 *
 * This header is the single source of truth for both the device executor and
 * the host-side protocol reader.  The protocol describes execution semantics,
 * not named workloads or particular engine pairs: at most three typed lanes
 * are executed for at most four rounds.  Two lanes cover pair/hazard
 * calibration; a three-lane disjoint window can represent movement + compute +
 * writeback without baking that workload into the schema.  Engine-specific
 * packet construction stays behind WaferNccProbeEngineAdapter.
 */

#define WAFER_NCC_PROTOCOL_REQUEST_MAGIC UINT64_C(0x3251455243434e57)
#define WAFER_NCC_PROTOCOL_RECORD_MAGIC UINT64_C(0x3243455843434e57)
#define WAFER_NCC_PROTOCOL_SCHEMA 7U
#define WAFER_NCC_PROTOCOL_REQUEST_WORDS 58U
#define WAFER_NCC_PROTOCOL_RECORD_WORDS 404U
#define WAFER_NCC_PROTOCOL_MAX_LANES 3U
#define WAFER_NCC_PROTOCOL_MAX_ROUNDS 4U
#define WAFER_NCC_PROTOCOL_MAX_ISSUES 12U
#define WAFER_NCC_PROTOCOL_WORKERS 3U
#define WAFER_NCC_PROTOCOL_MAX_DMA_ENVELOPE_BYTES 65536U
#define WAFER_NCC_PROTOCOL_DMA_FORMAT_FP16 2U
#define WAFER_NCC_PROTOCOL_REQUEST_RESERVED_BASE 16U
#define WAFER_NCC_PROTOCOL_REQUEST_RESERVED_WORDS 0U
#define WAFER_NCC_PROTOCOL_LANE_BASE 16U
#define WAFER_NCC_PROTOCOL_LANE_STRIDE 14U
#define WAFER_NCC_PROTOCOL_ISSUE_BASE 128U
#define WAFER_NCC_PROTOCOL_ISSUE_STRIDE 22U
#define WAFER_NCC_PROTOCOL_WAIT_SAMPLE_BASE 392U
#define WAFER_NCC_PROTOCOL_MAX_WAIT_SAMPLES 8U

enum WaferNccProtocolCommand {
  WAFER_NCC_COMMAND_QUALIFY = 0,
  WAFER_NCC_COMMAND_EXECUTE = 1,
};

enum WaferNccProtocolEngine {
  WAFER_NCC_ENGINE_CT = 0,
  WAFER_NCC_ENGINE_NE = 1,
  WAFER_NCC_ENGINE_RDMA = 2,
  WAFER_NCC_ENGINE_WDMA = 3,
  WAFER_NCC_ENGINE_TDMA = 4,
  WAFER_NCC_ENGINE_NONE = 255,
};

enum WaferNccProtocolEffectRelation {
  WAFER_NCC_EFFECT_NONE = 0,
  WAFER_NCC_EFFECT_RAW = 1,
  WAFER_NCC_EFFECT_WAR = 2,
  WAFER_NCC_EFFECT_WAW = 3,
  WAFER_NCC_EFFECT_RAR = 4,
};

enum WaferNccProtocolRangeRelation {
  WAFER_NCC_RANGE_DISJOINT = 0,
  WAFER_NCC_RANGE_EXACT = 1,
  WAFER_NCC_RANGE_PARTIAL = 2,
  WAFER_NCC_RANGE_ADJACENT = 3,
  WAFER_NCC_RANGE_STRIDED_ENVELOPE = 4,
};

enum WaferNccProtocolSchedule {
  WAFER_NCC_SCHEDULE_WINDOW = 0,
  WAFER_NCC_SCHEDULE_SERIAL = 1,
};

enum WaferNccProtocolWaitKind {
  WAFER_NCC_WAIT_NONE = 0,
  WAFER_NCC_WAIT_BY_WORKER = 1,
  WAFER_NCC_WAIT_DEFAULT = 2,
  WAFER_NCC_WAIT_LOCAL_FENCE = 3,
};

enum WaferNccProtocolIssueMode {
  WAFER_NCC_ISSUE_RAW = 0,
  WAFER_NCC_ISSUE_WRAPPER = 1,
};

enum WaferNccProtocolLayoutKind {
  WAFER_NCC_LAYOUT_CONTIGUOUS = 0,
  WAFER_NCC_LAYOUT_INNER_STRIDED = 1,
  WAFER_NCC_LAYOUT_DMA_STRIDED = 2,
};

enum WaferNccProtocolOraclePhase {
  WAFER_NCC_ORACLE_BOUNDARY = 0,
  WAFER_NCC_ORACLE_FINAL = 1,
};

enum WaferNccProtocolStatus {
  WAFER_NCC_STATUS_OK = 0,
  WAFER_NCC_STATUS_BAD_REQUEST = 1,
  WAFER_NCC_STATUS_MISSING_ADAPTER = 2,
  WAFER_NCC_STATUS_UNSUPPORTED_COMBINATION = 3,
  WAFER_NCC_STATUS_UNSAFE_WINDOW = 4,
  WAFER_NCC_STATUS_SEED_FAILED = 5,
  WAFER_NCC_STATUS_PREPARE_FAILED = 6,
  WAFER_NCC_STATUS_ISSUE_FAILED = 7,
  WAFER_NCC_STATUS_OBSERVATION_FAILED = 8,
  WAFER_NCC_STATUS_WAIT_FAILED = 9,
  WAFER_NCC_STATUS_DRAIN_FAILED = 10,
};

enum WaferNccProtocolRecordFlag {
  WAFER_NCC_RECORD_BEFORE_CAPTURED = UINT32_C(1) << 0,
  WAFER_NCC_RECORD_REQUESTED_WAIT_DONE = UINT32_C(1) << 1,
  WAFER_NCC_RECORD_BOUNDARY_CAPTURED = UINT32_C(1) << 2,
  WAFER_NCC_RECORD_BOUNDARY_ORACLE_DONE = UINT32_C(1) << 3,
  WAFER_NCC_RECORD_SAFETY_DRAIN_DONE = UINT32_C(1) << 4,
  WAFER_NCC_RECORD_FINAL_CAPTURED = UINT32_C(1) << 5,
  WAFER_NCC_RECORD_FINAL_ORACLE_DONE = UINT32_C(1) << 6,
  WAFER_NCC_RECORD_CONSTRUCTOR_CAPTURED = UINT32_C(1) << 7,
  WAFER_NCC_RECORD_PREISSUE_LOCAL_WAIT_DONE = UINT32_C(1) << 8,
  WAFER_NCC_RECORD_PRE_WAIT_CAPTURED = UINT32_C(1) << 9,
};

enum WaferNccProtocolRequestFlag {
  WAFER_NCC_REQUEST_TIGHT_DEPTH_PLUS_ONE = UINT32_C(1) << 0,
  WAFER_NCC_REQUEST_CONSTRUCTOR_OBSERVATION = UINT32_C(1) << 1,
  WAFER_NCC_REQUEST_ORDERED_PRODUCER_CONSUMER = UINT32_C(1) << 2,
  WAFER_NCC_REQUEST_DOUBLE_SLOT_OBSERVATION = UINT32_C(1) << 3,
  WAFER_NCC_REQUEST_MAPPED_SPM_KCORE_WRITE = UINT32_C(1) << 4,
  WAFER_NCC_REQUEST_PREISSUE_LOCAL_WAIT = UINT32_C(1) << 5,
  WAFER_NCC_REQUEST_TIGHT_KCORE_BOUNDARY = UINT32_C(1) << 6,
  WAFER_NCC_REQUEST_TIGHT_QUEUE_SATURATION = UINT32_C(1) << 7,
  WAFER_NCC_REQUEST_TIGHT_WORKER_SCOPE = UINT32_C(1) << 8,
};

enum WaferNccProtocolMemoryEffect {
  WAFER_NCC_MEMORY_READ0 = UINT32_C(1) << 0,
  WAFER_NCC_MEMORY_READ1 = UINT32_C(1) << 1,
  WAFER_NCC_MEMORY_WRITE = UINT32_C(1) << 2,
};

enum WaferNccProtocolOperand {
  WAFER_NCC_OPERAND_READ0 = 0,
  WAFER_NCC_OPERAND_READ1 = 1,
  WAFER_NCC_OPERAND_WRITE = 2,
  WAFER_NCC_OPERAND_AUTO = 3,
};

enum WaferNccProtocolIssueFlag {
  WAFER_NCC_ISSUE_READ0_VALID = UINT32_C(1) << 0,
  WAFER_NCC_ISSUE_READ1_VALID = UINT32_C(1) << 1,
  WAFER_NCC_ISSUE_WRITE_VALID = UINT32_C(1) << 2,
  WAFER_NCC_ISSUE_PACKET_OBSERVED = UINT32_C(1) << 3,
  WAFER_NCC_ISSUE_WINDOW_CONTROL_VALID = UINT32_C(1) << 4,
};

/*
 * Preparation progress is retained only when preparation fails.  A
 * successful issue observation replaces these bits with the execution
 * observation flags above.  The generic executor owns ENTERED/COMPLETED; a
 * raw-packet adapter reports the three builder/materialization stages.
 */
#define WAFER_NCC_ISSUE_PREPARE_ENTERED (UINT64_C(1) << 32)
#define WAFER_NCC_ISSUE_PREPARE_BUILDER_ACQUIRED (UINT64_C(1) << 33)
#define WAFER_NCC_ISSUE_PREPARE_PACKET_MATERIALIZED (UINT64_C(1) << 34)
#define WAFER_NCC_ISSUE_PREPARE_BUILDER_RELEASED (UINT64_C(1) << 35)
#define WAFER_NCC_ISSUE_PREPARE_COMPLETED (UINT64_C(1) << 36)

enum WaferNccProtocolRequestWord {
  WAFER_NCC_REQ_MAGIC = 0,
  WAFER_NCC_REQ_SCHEMA_AND_WORDS = 1,
  WAFER_NCC_REQ_COMMAND = 2,
  WAFER_NCC_REQ_LANE_COUNT = 3,
  WAFER_NCC_REQ_ROUNDS = 4,
  WAFER_NCC_REQ_EFFECT_RELATION = 5,
  WAFER_NCC_REQ_RANGE_RELATION = 6,
  WAFER_NCC_REQ_SCHEDULE = 7,
  WAFER_NCC_REQ_WAIT_KIND = 8,
  WAFER_NCC_REQ_WAIT_WORKER_MASK = 9,
  WAFER_NCC_REQ_SEED = 10,
  WAFER_NCC_REQ_SAMPLE = 11,
  WAFER_NCC_REQ_FLAGS = 12,
  WAFER_NCC_REQ_FIRST_OPERAND = 13,
  WAFER_NCC_REQ_SECOND_OPERAND = 14,
  WAFER_NCC_REQ_ISSUE_LIMIT = 15,
};

enum WaferNccProtocolLaneWord {
  WAFER_NCC_LANE_ENGINE = 0,
  WAFER_NCC_LANE_WORKER = 1,
  WAFER_NCC_LANE_ISSUE_MODE = 2,
  WAFER_NCC_LANE_TRANSFER_BYTES = 3,
  WAFER_NCC_LANE_ELEMENT_FORMAT = 4,
  WAFER_NCC_LANE_LAYOUT_KIND = 5,
  WAFER_NCC_LANE_LAYOUT_INNER_BYTES = 6,
  WAFER_NCC_LANE_LAYOUT_STRIDE0_BYTES = 7,
  WAFER_NCC_LANE_LAYOUT_STRIDE1_BYTES = 8,
  WAFER_NCC_LANE_LAYOUT_STRIDE2_BYTES = 9,
  WAFER_NCC_LANE_LAYOUT_ITERATION0 = 10,
  WAFER_NCC_LANE_LAYOUT_ITERATION1 = 11,
  WAFER_NCC_LANE_LAYOUT_ITERATION2 = 12,
  WAFER_NCC_LANE_FLAGS = 13,
};

enum WaferNccProtocolRecordWord {
  WAFER_NCC_REC_MAGIC = 0,
  WAFER_NCC_REC_SCHEMA_AND_WORDS = 1,
  WAFER_NCC_REC_STATUS = 2,
  WAFER_NCC_REC_FLAGS = 3,
  WAFER_NCC_REC_COMMAND = 4,
  WAFER_NCC_REC_LANE_COUNT = 5,
  WAFER_NCC_REC_ROUNDS = 6,
  WAFER_NCC_REC_ISSUE_COUNT = 7,
  WAFER_NCC_REC_EFFECT_RELATION = 8,
  WAFER_NCC_REC_RANGE_RELATION = 9,
  WAFER_NCC_REC_SCHEDULE = 10,
  WAFER_NCC_REC_WAIT_KIND = 11,
  WAFER_NCC_REC_WAIT_WORKER_MASK = 12,
  WAFER_NCC_REC_SAFETY_WORKER_MASK = 13,
  WAFER_NCC_REC_SEED = 14,
  WAFER_NCC_REC_SAMPLE = 15,
  WAFER_NCC_REC_BOUNDARY_MISMATCHES = 16,
  WAFER_NCC_REC_FINAL_MISMATCHES = 17,
  WAFER_NCC_REC_BOUNDARY_GUARD_MISMATCHES = 18,
  WAFER_NCC_REC_FINAL_GUARD_MISMATCHES = 19,
  WAFER_NCC_REC_STABLE_BEFORE = 20,
  WAFER_NCC_REC_STABLE_AFTER = 21,
  WAFER_NCC_REC_FIRST_OPERAND = 22,
  WAFER_NCC_REC_SECOND_OPERAND = 23,
  WAFER_NCC_REC_CONTROL_BEFORE = 24,
  WAFER_NCC_REC_CONTROL_BOUNDARY = 27,
  WAFER_NCC_REC_CONTROL_FINAL = 30,
  WAFER_NCC_REC_PMU64_BEFORE = 33,
  WAFER_NCC_REC_PMU64_AFTER = 41,
  WAFER_NCC_REC_INSTRUCTION_BEFORE = 49,
  WAFER_NCC_REC_INSTRUCTION_AFTER = 64,
  WAFER_NCC_REC_BLOCKING_BEFORE = 79,
  WAFER_NCC_REC_BLOCKING_AFTER = 94,
  WAFER_NCC_REC_PMU_ENABLE = 109,
  WAFER_NCC_REC_SERIAL_MODE = 110,
  WAFER_NCC_REC_OUTPUT_SLOT_BASE = 113,
  WAFER_NCC_REC_OUTPUT_SLOT_STRIDE = 114,
  WAFER_NCC_REC_OUTPUT_GUARD_BYTES = 115,
  WAFER_NCC_REC_RESOURCE_BYTES = 116,
  WAFER_NCC_REC_ISSUE_LIMIT = 117,
  WAFER_NCC_REC_WAIT_CYCLES = 118,
  WAFER_NCC_REC_COMPLETION_MARKER_EXPECTED = 119,
  WAFER_NCC_REC_COMPLETION_MARKER_BOUNDARY = 120,
  WAFER_NCC_REC_COMPLETION_MARKER_FINAL = 121,
  WAFER_NCC_REC_COMPLETION_MARKER_ADDRESS = 122,
  WAFER_NCC_REC_PLAN_CYCLES = 123,
  WAFER_NCC_REC_SERIAL_WAIT_CYCLES = 124,
  WAFER_NCC_REC_SERIAL_WAIT_COUNT = 125,
  WAFER_NCC_REC_CONSTRUCTOR_ADDRESS = 126,
  WAFER_NCC_REC_RECORD_GUARD = 127,
  WAFER_NCC_REC_PREISSUE_WAIT_CYCLES = 400,
  WAFER_NCC_REC_CONTROL_PRE_WAIT = 401,
};

enum WaferNccProtocolIssueWord {
  WAFER_NCC_ISSUE_ORDINAL = 0,
  WAFER_NCC_ISSUE_LANE = 1,
  WAFER_NCC_ISSUE_ROUND = 2,
  WAFER_NCC_ISSUE_SLOT = 3,
  WAFER_NCC_ISSUE_ENGINE = 4,
  WAFER_NCC_ISSUE_WORKER = 5,
  WAFER_NCC_ISSUE_TAG = 6,
  WAFER_NCC_ISSUE_EXECUTE_RC = 7,
  WAFER_NCC_ISSUE_INTER_TYPE = 8,
  WAFER_NCC_ISSUE_READ0_BEGIN = 9,
  WAFER_NCC_ISSUE_READ0_END = 10,
  WAFER_NCC_ISSUE_READ1_BEGIN = 11,
  WAFER_NCC_ISSUE_READ1_END = 12,
  WAFER_NCC_ISSUE_WRITE_BEGIN = 13,
  WAFER_NCC_ISSUE_WRITE_END = 14,
  WAFER_NCC_ISSUE_BOUNDARY_MISMATCHES = 15,
  WAFER_NCC_ISSUE_BOUNDARY_GUARD_MISMATCHES = 16,
  WAFER_NCC_ISSUE_FINAL_MISMATCHES = 17,
  WAFER_NCC_ISSUE_FINAL_GUARD_MISMATCHES = 18,
  WAFER_NCC_ISSUE_FLAGS = 19,
  WAFER_NCC_ISSUE_CONTROL_AFTER_ISSUE = 20,
  WAFER_NCC_ISSUE_EXECUTE_CYCLES = 21,
};

static inline uint32_t wafer_ncc_protocol_lane_word(uint32_t lane,
                                                    uint32_t field) {
  return WAFER_NCC_PROTOCOL_LANE_BASE +
         lane * WAFER_NCC_PROTOCOL_LANE_STRIDE + field;
}

static inline uint32_t wafer_ncc_protocol_issue_word(uint32_t issue,
                                                     uint32_t field) {
  return WAFER_NCC_PROTOCOL_ISSUE_BASE +
         issue * WAFER_NCC_PROTOCOL_ISSUE_STRIDE + field;
}

#endif
