#!/usr/bin/env python3
"""Emit a compilable C ABI skeleton from a Wafer package manifest."""

from __future__ import annotations

import argparse
import pathlib
import re
import sys


SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from wafer_package_manifest import load_manifest, validate_manifest  # noqa: E402


OP_ENUMS = {
    "wafer.abi.rdma_1d": "WAFER_ABI_RDMA_1D",
    "wafer.abi.wdma_1d": "WAFER_ABI_WDMA_1D",
    "wafer.abi.gemm": "WAFER_ABI_GEMM",
}


def c_ident(name: str) -> str:
    ident = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not ident or ident[0].isdigit():
        ident = f"_{ident}"
    return ident


def emit_c(manifest: dict) -> str:
    validate_manifest(manifest)
    package_ident = c_ident(manifest["package_name"])
    abi_ops = manifest["abi_ops"]

    lines = [
        "/* Generated by wafer_emit_c_abi_stub.py. */",
        "#include <stdint.h>",
        "",
        "typedef enum {",
        "  WAFER_WAIT_ISSUE_ONLY = 0,",
        "} wafer_wait_policy_t;",
        "",
        "typedef enum {",
        "  WAFER_ABI_RDMA_1D = 1,",
        "  WAFER_ABI_WDMA_1D = 2,",
        "  WAFER_ABI_GEMM = 3,",
        "} wafer_abi_op_t;",
        "",
        "typedef struct {",
        "  wafer_abi_op_t op;",
        "  uint64_t bytes;",
        "  int64_t m;",
        "  int64_t k;",
        "  int64_t n;",
        "  wafer_wait_policy_t wait_policy;",
        "} wafer_abi_issue_t;",
        "",
        f"static const wafer_abi_issue_t k_{package_ident}_issues[] = {{",
    ]

    for op in abi_ops:
        mnemonic = op["op"]
        enum_name = OP_ENUMS[mnemonic]
        bytes_value = int(op.get("bytes", 0))
        m = int(op.get("m", 0))
        k = int(op.get("k", 0))
        n = int(op.get("n", 0))
        lines.append(
            f"  {{{enum_name}, {bytes_value}u, {m}, {k}, {n}, "
            "WAFER_WAIT_ISSUE_ONLY},"
        )

    lines.extend(
        [
            "};",
            "",
            f"int {package_ident}_issue_count(void) {{",
            f"  return (int)(sizeof(k_{package_ident}_issues) / "
            f"sizeof(k_{package_ident}_issues[0]));",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True)
    args = parser.parse_args()

    manifest = load_manifest(args.manifest)
    sys.stdout.write(emit_c(manifest))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1)
