#!/usr/bin/env python3
"""Emit a compilable C ABI skeleton from a Wafer package manifest."""

from __future__ import annotations

import argparse
import pathlib
import re
import sys


SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from wafer_package_manifest import load_manifest, validate_manifest  # noqa: E402


OP_ENUMS = {
    "wafer.abi.rdma_1d": "WAFER_ABI_RDMA_1D",
    "wafer.abi.wdma_1d": "WAFER_ABI_WDMA_1D",
    "wafer.abi.gemm": "WAFER_ABI_GEMM",
    "wafer.abi.elementwise": "WAFER_ABI_ELEMENTWISE",
}

ELEMENTWISE_ENUMS = {
    "add": "WAFER_ELEMENTWISE_ADD",
    "sub": "WAFER_ELEMENTWISE_SUB",
    "mul": "WAFER_ELEMENTWISE_MUL",
    "div": "WAFER_ELEMENTWISE_DIV",
    "max": "WAFER_ELEMENTWISE_MAX",
    "min": "WAFER_ELEMENTWISE_MIN",
    "neg": "WAFER_ELEMENTWISE_NEG",
    "recip": "WAFER_ELEMENTWISE_RECIP",
    "sqrt": "WAFER_ELEMENTWISE_SQRT",
    "rsqrt": "WAFER_ELEMENTWISE_RSQRT",
    "exp": "WAFER_ELEMENTWISE_EXP",
    "tanh": "WAFER_ELEMENTWISE_TANH",
}


def c_ident(name: str) -> str:
    ident = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not ident or ident[0].isdigit():
        ident = f"_{ident}"
    return ident


def emit_c(manifest: dict) -> str:
    validate_manifest(manifest)
    package_ident = c_ident(manifest["package_name"])
    abi_ops = manifest["abi_ops"]
    placement_ranks = sorted(
        manifest["placement"]["ranks"], key=lambda item: int(item["logical_rank"])
    )

    lines = [
        "/* Generated by wafer_emit_c_abi_stub.py. */",
        "#include <stdint.h>",
        "",
        "typedef enum {",
        "  WAFER_WAIT_ISSUE_ONLY = 0,",
        "} wafer_wait_policy_t;",
        "",
        "typedef enum {",
        "  WAFER_ABI_RDMA_1D = 1,",
        "  WAFER_ABI_WDMA_1D = 2,",
        "  WAFER_ABI_GEMM = 3,",
        "  WAFER_ABI_ELEMENTWISE = 4,",
        "} wafer_abi_op_t;",
        "",
        "typedef enum {",
        "  WAFER_ELEMENTWISE_NONE = 0,",
        "  WAFER_ELEMENTWISE_ADD = 1,",
        "  WAFER_ELEMENTWISE_SUB = 2,",
        "  WAFER_ELEMENTWISE_MUL = 3,",
        "  WAFER_ELEMENTWISE_DIV = 4,",
        "  WAFER_ELEMENTWISE_MAX = 5,",
        "  WAFER_ELEMENTWISE_MIN = 6,",
        "  WAFER_ELEMENTWISE_NEG = 7,",
        "  WAFER_ELEMENTWISE_RECIP = 8,",
        "  WAFER_ELEMENTWISE_SQRT = 9,",
        "  WAFER_ELEMENTWISE_RSQRT = 10,",
        "  WAFER_ELEMENTWISE_EXP = 11,",
        "  WAFER_ELEMENTWISE_TANH = 12,",
        "} wafer_elementwise_kind_t;",
        "",
        "typedef struct {",
        "  wafer_abi_op_t op;",
        "  uint64_t bytes;",
        "  int64_t m;",
        "  int64_t k;",
        "  int64_t n;",
        "  wafer_elementwise_kind_t elementwise_kind;",
        "  wafer_wait_policy_t wait_policy;",
        "} wafer_abi_issue_t;",
        "",
        "typedef struct {",
        "  uint32_t logical_rank;",
        "  uint32_t block_id;",
        "  uint32_t card_y;",
        "  uint32_t card_x;",
        "  uint32_t tile_y;",
        "  uint32_t tile_x;",
        "} wafer_tile_launch_arg_t;",
        "",
        f"static const wafer_abi_issue_t k_{package_ident}_issues[] = {{",
    ]

    for op in abi_ops:
        mnemonic = op["op"]
        enum_name = OP_ENUMS[mnemonic]
        bytes_value = int(op.get("bytes", 0))
        m = int(op.get("m", 0))
        k = int(op.get("k", 0))
        n = int(op.get("n", 0))
        elementwise_kind = ELEMENTWISE_ENUMS.get(op.get("kind", ""), "WAFER_ELEMENTWISE_NONE")
        lines.append(
            f"  {{{enum_name}, {bytes_value}u, {m}, {k}, {n}, {elementwise_kind}, "
            "WAFER_WAIT_ISSUE_ONLY},"
        )

    lines.extend(
        [
            "};",
            "",
            f"int {package_ident}_issue_count(void) {{",
            f"  return (int)(sizeof(k_{package_ident}_issues) / "
            f"sizeof(k_{package_ident}_issues[0]));",
            "}",
            "",
            f"static const wafer_tile_launch_arg_t k_{package_ident}_tile_args[] = {{",
        ]
    )

    for rank in placement_ranks:
        coord = rank["physical_coord"]
        lines.append(
            f"  {{{int(rank['logical_rank'])}u, {int(rank['block_id'])}u, "
            f"{int(coord[0])}u, {int(coord[1])}u, {int(coord[2])}u, "
            f"{int(coord[3])}u}},"
        )

    lines.extend(
        [
            "};",
            "",
            f"int {package_ident}_tile_arg_count(void) {{",
            f"  return (int)(sizeof(k_{package_ident}_tile_args) / "
            f"sizeof(k_{package_ident}_tile_args[0]));",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True)
    args = parser.parse_args()

    manifest = load_manifest(args.manifest)
    sys.stdout.write(emit_c(manifest))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1)
