#!/usr/bin/env python3
"""Emit a compilable C ABI issue sequence from Wafer package metadata."""

from __future__ import annotations

import argparse
import pathlib
import re
import sys


SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from wafer_package_metadata import load_package_metadata, validate_package_metadata  # noqa: E402


OP_ENUMS = {
    "wafer.instr.rdma": "WAFER_INSTR_RDMA",
    "wafer.instr.wdma": "WAFER_INSTR_WDMA",
    "wafer.instr.gather_scatter": "WAFER_INSTR_GATHER_SCATTER",
    "wafer.instr.fill": "WAFER_INSTR_FILL",
    "wafer.instr.gemm": "WAFER_INSTR_GEMM",
    "wafer.instr.elementwise": "WAFER_INSTR_ELEMENTWISE",
    "wafer.instr.reduce": "WAFER_INSTR_REDUCE",
    "wafer.instr.convert": "WAFER_INSTR_CONVERT",
    "wafer.instr.dte_send": "WAFER_INSTR_DTE_SEND",
    "wafer.instr.dte_recv": "WAFER_INSTR_DTE_RECV",
    "wafer.instr.dte_wait": "WAFER_INSTR_DTE_WAIT",
    "wafer.instr.local_fence": "WAFER_INSTR_LOCAL_FENCE",
}

ELEMENTWISE_ENUMS = {
    "add": "WAFER_ELEMENTWISE_ADD",
    "sub": "WAFER_ELEMENTWISE_SUB",
    "mul": "WAFER_ELEMENTWISE_MUL",
    "div": "WAFER_ELEMENTWISE_DIV",
    "max": "WAFER_ELEMENTWISE_MAX",
    "min": "WAFER_ELEMENTWISE_MIN",
    "neg": "WAFER_ELEMENTWISE_NEG",
    "recip": "WAFER_ELEMENTWISE_RECIP",
    "sqrt": "WAFER_ELEMENTWISE_SQRT",
    "rsqrt": "WAFER_ELEMENTWISE_RSQRT",
    "exp": "WAFER_ELEMENTWISE_EXP",
    "tanh": "WAFER_ELEMENTWISE_TANH",
    "eq": "WAFER_ELEMENTWISE_EQ",
    "ne": "WAFER_ELEMENTWISE_NE",
    "lt": "WAFER_ELEMENTWISE_LT",
    "le": "WAFER_ELEMENTWISE_LE",
    "gt": "WAFER_ELEMENTWISE_GT",
    "ge": "WAFER_ELEMENTWISE_GE",
    "select": "WAFER_ELEMENTWISE_SELECT",
}

REDUCE_ENUMS = {
    "sum": "WAFER_REDUCE_SUM",
    "max": "WAFER_REDUCE_MAX",
    "min": "WAFER_REDUCE_MIN",
    "avg": "WAFER_REDUCE_AVG",
}


def c_ident(name: str) -> str:
    ident = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not ident or ident[0].isdigit():
        ident = f"_{ident}"
    return ident


def format_c_float(value: int | float | dict) -> str:
    if isinstance(value, dict):
        if value.get("kind") != "non_finite":
            raise ValueError("unsupported structured C float value")
        encoded = value.get("value")
        if encoded == "-inf":
            return "-__builtin_inf()"
        if encoded == "inf":
            return "__builtin_inf()"
        if encoded == "nan":
            return "__builtin_nan(\"\")"
        raise ValueError("unsupported non-finite C float value")
    return format(float(value), ".9g")


def emit_c(metadata: dict) -> str:
    validate_package_metadata(metadata)
    package_ident = c_ident(metadata["name"])
    instructions = metadata["instructions"]
    interface = metadata["model"]["interface"]
    workspace_buffers = interface["workspace"]
    resident_constants = interface["resident_constants"]

    lines = [
        "/* Generated by wafer_emit_c_abi_stub.py. */",
        "#include <stdint.h>",
        "",
        "typedef enum {",
        "  WAFER_WAIT_ISSUE_ONLY = 0,",
        "  WAFER_WAIT_LOCAL_WAIT = 1,",
        "} wafer_wait_policy_t;",
        "",
        "typedef enum {",
        "  WAFER_INSTR_RDMA = 1,",
        "  WAFER_INSTR_WDMA = 2,",
        "  WAFER_INSTR_GATHER_SCATTER = 3,",
        "  WAFER_INSTR_FILL = 4,",
        "  WAFER_INSTR_ELEMENTWISE = 5,",
        "  WAFER_INSTR_REDUCE = 6,",
        "  WAFER_INSTR_CONVERT = 7,",
        "  WAFER_INSTR_GEMM = 8,",
        "  WAFER_INSTR_DTE_SEND = 9,",
        "  WAFER_INSTR_DTE_RECV = 10,",
        "  WAFER_INSTR_DTE_WAIT = 11,",
        "  WAFER_INSTR_LOCAL_FENCE = 12,",
        "} wafer_instruction_op_t;",
        "",
        "typedef enum {",
        "  WAFER_ELEMENTWISE_NONE = 0,",
        "  WAFER_ELEMENTWISE_ADD = 1,",
        "  WAFER_ELEMENTWISE_SUB = 2,",
        "  WAFER_ELEMENTWISE_MUL = 3,",
        "  WAFER_ELEMENTWISE_DIV = 4,",
        "  WAFER_ELEMENTWISE_MAX = 5,",
        "  WAFER_ELEMENTWISE_MIN = 6,",
        "  WAFER_ELEMENTWISE_NEG = 7,",
        "  WAFER_ELEMENTWISE_RECIP = 8,",
        "  WAFER_ELEMENTWISE_SQRT = 9,",
        "  WAFER_ELEMENTWISE_RSQRT = 10,",
        "  WAFER_ELEMENTWISE_EXP = 11,",
        "  WAFER_ELEMENTWISE_TANH = 12,",
        "  WAFER_ELEMENTWISE_EQ = 13,",
        "  WAFER_ELEMENTWISE_NE = 14,",
        "  WAFER_ELEMENTWISE_LT = 15,",
        "  WAFER_ELEMENTWISE_LE = 16,",
        "  WAFER_ELEMENTWISE_GT = 17,",
        "  WAFER_ELEMENTWISE_GE = 18,",
        "  WAFER_ELEMENTWISE_SELECT = 19,",
        "} wafer_elementwise_kind_t;",
        "",
        "typedef enum {",
        "  WAFER_REDUCE_NONE = 0,",
        "  WAFER_REDUCE_SUM = 1,",
        "  WAFER_REDUCE_MAX = 2,",
        "  WAFER_REDUCE_MIN = 3,",
        "  WAFER_REDUCE_AVG = 4,",
        "} wafer_reduce_kind_t;",
        "",
        "typedef struct {",
        "  wafer_instruction_op_t op;",
        "  uint64_t bytes;",
        "  int64_t m;",
        "  int64_t k;",
        "  int64_t n;",
        "  int64_t batch_count;",
        "  wafer_elementwise_kind_t elementwise_kind;",
        "  wafer_reduce_kind_t reduce_kind;",
        "  uint32_t reduce_dimension_count;",
        "  int64_t reduce_dimensions[4];",
        "  double reduce_init_value;",
        "  wafer_wait_policy_t wait_policy;",
        "} wafer_instruction_issue_t;",
        "",
        "typedef struct {",
        "  uint64_t bytes;",
        "  uint64_t alignment;",
        "} wafer_workspace_buffer_t;",
        "",
        "typedef struct {",
        "  uint64_t bytes;",
        "  uint64_t alignment;",
        "} wafer_resident_constant_t;",
        "",
        f"static const wafer_instruction_issue_t k_{package_ident}_issues[] = {{",
    ]

    for op in instructions:
        mnemonic = op["op"]
        enum_name = OP_ENUMS[mnemonic]
        bytes_value = int(op.get("bytes", 0))
        m = int(op.get("m", 0))
        k = int(op.get("k", 0))
        n = int(op.get("n", 0))
        default_batch_count = 1 if mnemonic == "wafer.instr.gemm" else 0
        batch_count = int(op.get("batch_count", default_batch_count))
        elementwise_kind = "WAFER_ELEMENTWISE_NONE"
        if mnemonic == "wafer.instr.elementwise":
            elementwise_kind = ELEMENTWISE_ENUMS[op["kind"]]
        reduce_kind = "WAFER_REDUCE_NONE"
        if mnemonic == "wafer.instr.reduce":
            reduce_kind = REDUCE_ENUMS[op["kind"]]
        reduce_dimensions = [int(dim) for dim in op.get("dimensions", [])]
        padded_reduce_dimensions = (reduce_dimensions + [0, 0, 0, 0])[:4]
        reduce_dimensions_text = ", ".join(
            str(dim) for dim in padded_reduce_dimensions
        )
        reduce_init_value = format_c_float(op.get("init_value", 0))
        wait_policy = {
            "issue_only": "WAFER_WAIT_ISSUE_ONLY",
            "local_wait": "WAFER_WAIT_LOCAL_WAIT",
        }[op.get("wait_policy", "issue_only")]
        lines.append(
            f"  {{{enum_name}, {bytes_value}u, {m}, {k}, {n}, {batch_count}, "
            f"{elementwise_kind}, {reduce_kind}, {len(reduce_dimensions)}u, "
            f"{{{reduce_dimensions_text}}}, {reduce_init_value}, "
            f"{wait_policy}}},"
        )

    lines.extend(
        [
            "};",
            "",
            f"int {package_ident}_issue_count(void) {{",
            f"  return (int)(sizeof(k_{package_ident}_issues) / "
            f"sizeof(k_{package_ident}_issues[0]));",
            "}",
            "",
        ]
    )

    lines.append(
        f"static const wafer_workspace_buffer_t "
        f"k_{package_ident}_workspace_buffers[] = {{"
    )
    for buffer in workspace_buffers:
        lines.append(f"  {{{int(buffer['bytes'])}u, {int(buffer['alignment'])}u}},")
    lines.extend(
        [
            "};",
            "",
            f"int {package_ident}_workspace_buffer_count(void) {{",
            f"  return (int)(sizeof(k_{package_ident}_workspace_buffers) / "
            f"sizeof(k_{package_ident}_workspace_buffers[0]));",
            "}",
            "",
            f"static const wafer_resident_constant_t "
            f"k_{package_ident}_resident_constants[] = {{",
        ]
    )
    for constant in resident_constants:
        lines.append(
            f"  {{{int(constant['bytes'])}u, {int(constant['alignment'])}u}},"
        )
    lines.extend(
        [
            "};",
            "",
            f"int {package_ident}_resident_constant_count(void) {{",
            f"  return (int)(sizeof(k_{package_ident}_resident_constants) / "
            f"sizeof(k_{package_ident}_resident_constants[0]));",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--package-metadata", required=True)
    args = parser.parse_args()

    metadata = load_package_metadata(args.package_metadata)
    sys.stdout.write(emit_c(metadata))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1)
